### ISSUE TITLE
Proposal: Use bookdown for generating course material

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#10]
## Proposal

Using the R package [bookdown](https://github.com/rstudio/bookdown) ([documentation](https://bookdown.org/yihui/bookdown/)) for creating the material meets all of the requirements as stated in #3.

## Background

Bookdown is a package that generates HTML, PDF, and many other "book" type output from a single Markdown source. It uses [knitr](https://yihui.name/knitr/) and [rmarkdown](https://rmarkdown.rstudio.com/) under the hood, so R code (or [Python code](https://bookdown.org/yihui/rmarkdown/language-engines.html) if the knitr engine is set to Python) can be included, ran, and the output inserted into the document easily. All features necessary for writing books (cross-referencing, citations, table of content, linkage, etc) are available.

R Markdown is very commonly used, highly refined, and well maintained document writing format. Through knitr, we can do a wide range of tasks that can be very useful for a course setting (e.g. by including hidden solution code) or by including "child documents" (as commented in #3). Plus, as an added bonus, through the [reticulate](https://rstudio.github.io/reticulate/) package, R and Python output can be shared within the same Markdown document. R Markdown uses Pandoc under the hood, which is a very well-maintained and used Markdown converter.

Bookdown is also widely used by the RStudio team (and many other groups, such as the rOpenSci team) for creating full length documentation. See the bookdown [archive](https://bookdown.org/home/archive/) for a list of books made with bookdown.

Since bookdown is a package, most tasks are handled automatically or programmatically, so generating the source material into various output can be easily done and further automated through travis.

## Pros and cons

**Pros**:

- Reviewable on GitHub (much nicer than Jupyter notebook)
- Can use both R and Python
- Can autogenerate a wide range of output formats for both web (suited for multiple device type too) and print
- We can pass parameters through the YAML header to be accessible within the document (as per @gvwilson comment in #3)
- Using R Markdown matches how reproducible research would also look like (you can publish theses via thesisdown, posters via posterdown (in dev), slides via xaringan (and others), articles via rticles, and blogs via blogdown... all from R Markdown). That way our tools match what we are teaching.
- If we don't like bookdown or want to convert to something else later, this isn't a big problem given that rmarkdown can render to any output format (via pandoc)
- We can render the book locally for local development
- Has all book writing needs
- Since the source material is Markdown, you can use any text editor of your choice if you don't know or like to use RStudio... though I must admit that RStudio is exactly suited for working with R Markdown (I have a bias, I know)
- I could go on but I won't :stuck_out_tongue_winking_eye: 

**Cons**:

- I'm not 100% certain about the gitbook issue that @gvwilson raised in #3. It [seems](https://bookdown.org/yihui/bookdown/html.html) that bookdown only mimics the gitbook output, but doesn't actually use it. If gitbook output isn't wanted, there are two other options available.
- I personally haven't tried running R Markdown with Python code chunks so I can't confirm what the experience is like there, but I've seen others and other websites do it.
- If you are much more familiar/comfortable working in Jupyter, then I think there may be a problem. I haven't used Jupyter much, so I don't know how it would handle opening Markdown documents.
- I'm really not sure what other cons there are. 

## Possible alternatives

Several are already listed in #3

**Comment by gvwilson** [comment]
Approved in #7.
