### ISSUE TITLE
Novice Python section assignment: Data Manipulation

### ISSUE THREAD

**Issue by brandeism** [merely-useful/merely-useful.github.io#104]
This issue tracks the [Data Manipulation](https://github.com/merely-useful/merely-useful.github.io/blob/ab6b9e3a2cbad6c90bc128965bb9b403cfc88201/novice-goals.Rmd#L22-L49) section for the novice Python material.

This issue can be closed when:
- [x] There are an initial set of Python exercises corresponding to the outline
- [x] There is a first draft of the text of the section

**Comment by mbonsma** [comment]
Thanks @brandeism! Hoping to get at this soon.
