### ISSUE TITLE
Intermediate subsection: Shell

### ISSUE THREAD

**Issue by ljdursi** [merely-useful/merely-useful.github.io#105]
This issue tracks the [shell section](https://github.com/merely-useful/merely-useful.github.io/blob/feeef414acd83e3caee81113e0ffa79ab047e637/intermediate-goals.Rmd#L14-L53) in the intermediate material.

This issue can be closed when

- [x] There are an initial set of exercises corresponding to the outline of the material (which may evolve as part of this task)
- [x] There is a first draft of the text of the section

**Comment by ljdursi** [comment]
(Sorry, started doing these last week and just finishing them now)

**Comment by DamienIrving** [comment]
I'm anticipating that this lesson will be very similar (i.e. almost a direct cut and paste) of the [Software Carpentry shell lessons](http://swcarpentry.github.io/shell-novice/).

**Comment by DamienIrving** [comment]
The associated draft PR is #123

**Comment by DamienIrving** [comment]
Re-opening because I need to add the content on remote access from #157

**Comment by lwjohnst86** [comment]
Closing since as per the rse-goals, remotes were not included.
