### ISSUE TITLE
Intermediate section: Unit testing

### ISSUE THREAD

**Issue by ljdursi** [merely-useful/merely-useful.github.io#106]
This issue tracks the [testing section](https://github.com/merely-useful/merely-useful.github.io/blob/book/rse-goals.Rmd#L111-L133) in the intermediate material.

This issue can be closed when

- [x] There are an initial set of exercises corresponding to the outline of the material (which may evolve as part of this task)
- [x] There is a first draft of the text of the section

**Comment by ljdursi** [comment]
@katyhuff, in the [last meeting](https://github.com/merely-useful/merely-useful.github.io/wiki/Meeting-agenda-2019-05-28) we thought you would be a natural choice?

**Comment by katyhuff** [comment]
Thanks! Yes, I can take this on. Sorry I've been missigg the calls.
