### ISSUE TITLE
Novice Python section assignment: Getting Started

### ISSUE THREAD

**Issue by brandeism** [merely-useful/merely-useful.github.io#109]
This issue tracks the [Getting Started](https://github.com/merely-useful/merely-useful.github.io/blob/ab6b9e3a2cbad6c90bc128965bb9b403cfc88201/novice-goals.Rmd#L7-L20) section for the novice Python material.

This issue can be closed when:
- [x] There are an initial set of Python exercises corresponding to the outline
- [x] There is a first draft of the text of the section

**Comment by ChristinaLK** [comment]
Question: how much actual Python intro-stuff should I include here?  I could simply include sample code without explaining much about it (i.e. don't use the words `function`, `variable`, etc.) or I could do a proper little intro where I introduce a few concepts (those above + probably methods). What do people think? 

@k8hertweck, it looks like you're doing the parallel section for R, so I'd be especially interested in your perspective.

**Comment by ChristinaLK** [comment]
The exercises are ready for review.
