### ISSUE TITLE
Signup for Novice R

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#11]
Please add a comment to this issue if you would like to work on the novice R lesson initially. In your comment, please briefly describe your favorite example, exercise, or data set.

**Comment by aurielfournier** [comment]
👋 

I've had a lot of fun starting folks off recently in workshops with plotting, since I often teach ecologists I'm working with data from eBird (a citizen science database of birds sightings from around the world).

**Comment by lwjohnst86** [comment]
I'm down for this. (Note: May 10 to May 24 I am traveling a lot for confs, vacation, and R workshops).

I'll add my favorite items later.

**Comment by k8hertweck** [comment]
I'd be happy to work on the intro R section. I'm really enjoying data manipulation (especially with dplyr) lately, and would be pleased to be able to contribute to this section.

**Comment by cwickham** [comment]
I'd love to work on the intro to R section.  @aurielfournier I'm all for starting with plotting!  

I participated in a fun, zero code, data manipulation activity recently that went something like:

* introduce some data manipulation verbs like filter, mutate and select (without actual reference to code, just as operations you can do on data),
* introduce some data (literally a print out of a spreadsheet-like table on a piece of paper), and a question of interest,
* hand out various intermediate tables (again printed out on paper) and some operations (on separate pieces of paper) using the verbs introduced,
* get students to put the intermediate tables in order along with the operations needed to get from one table to the next, that would answer the question of interest.

It was a great reminder that novices to data manipulation don't just need to be taught the code to perform it, they building language to describe how data can be manipulated and how to combine manipulations in a meaningful way.  I.e. before writing any code, you have to decide what operations you need to do, and in what order they should be done.

**Comment by gvwilson** [comment]
People have indicated preferences.
