### ISSUE TITLE
Suggestions for material on testing in data science

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#113]
From @luizirber:

I really liked this talk by Jes Ford at PyCon 2019: https://www.youtube.com/watch?v=0ysyWk-ox-8

slides: https://github.com/jesford/testing-in-data-science/blob/pycon-version/intro-to-testing-presentation.pdf

And she also suggests starting with assertions and then get more sophisticated
over time, even getting to the point of using Hypothesis, and turns out that the
talk following hers was about Hypothesis
https://www.youtube.com/watch?v=KcyGUVzL7HA
slides and tutorial repo:
https://github.com/Zac-HD/escape-from-automanual-testing 

Also https://www.alexpghayes.com/blog/testing-statistical-software/

**Comment by gvwilson** [comment]
I enjoyed your checking-driven development post today and I just wanted to bring to your attention a Python library aimed at data pipeline checking called Great Expectations:
https://github.com/great-expectations/great_expectations
https://great-expectations.readthedocs.io/en/latest/
 
OKF’s Frictionless Data project also publishes the goodtables tool:
http://goodtables.io/
http://try.goodtables.io/

They also have a Python library:
https://github.com/frictionlessdata/goodtables-py

**Comment by joelostblom** [comment]
A few more packages to verify assumptions about data:

- https://github.com/TomAugspurger/engarde (Python)
- https://github.com/jnmclarty/validada (Python)
- https://github.com/ropensci/assertr (R)
