### ISSUE TITLE
Discussion: Consistent format for code, text

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#116]
Can we decide on a consistent format for functions, variable names, dataset variable names (optional), and directories?

I like:

- For functions: `functionname()` ending with the brackets.
- For variable/objects: `object_name` or whatever fits with the respective style guide.
- For directories: `foldername/` ending in a slash, compared to files that would be `filename`.

Thoughts? It would be nice to be consistent throughout the course, since I tend to follow the list above, but I notice not everyone does.

**Comment by joelostblom** [comment]
Agree on the above. Just to be clear, you do use `_` in function names also right? So it would be `function_name()` if it was two words? I think all object names should be snake_case (which is in accordance with both pep8 and the tidyverse style guide).

A few additional thoughts
- I vote for single quote `'` over double quote `"`. Except for in bash where it impacts expansions.
- For files in the current dir, do you prepend `./`? I tend to do so for myself for clarity, but don't have strong feelings either way.
- What about organization of multiple parameters within function calls? I prefer stacking horizontally with multiple parameters per line over vertical stacking with one parameter per line.

**Comment by cwickham** [comment]
On the `'` versus `"`: I prefer `"` because R will always use `"` when it prints strings.

**Comment by joelostblom** [comment]
IMO, column names should also be `snake_case`.

**Comment by DamienIrving** [comment]
Should the action here be to create a `style_guide.md` file that we update as we go?

**Comment by joelostblom** [comment]
@DamienIrving Yes, l can create that file, to collect our thoughts. I don't think we need to write down all recommendation, but can prefer to existing style guides and note exceptions and additions.

I think for R, the tidyverse guide can be followed largely (completely?) as is. For Python, I think referring to pep8 is a good base and then adding the specifics around dataframes and plotting.

One other (minor) formatting consideration for Python is how to format multiline method chains. I prefer the following

```
(dataframe
    .method()
    .method(short_arg)
    .method(
        long_arg1,
        long_arg2))
```

Overall, I don't think we should get hung up on formatting, just collecting thoughts.

**Comment by joelostblom** [comment]
Closing this since we have incorporated these comments into the style guide for authors. Feel free to open new issues or reopen this if you have new/different style recommendations.
