### ISSUE TITLE
Signup for Novice Python

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#12]
Please add a comment to this issue if you would like to work on the novice Python lesson initially. In your comment, please briefly describe your favorite example, exercise, or data set.

**Comment by ChristinaLK** [comment]
I would be happy to work on any of the materials, but this is probably the one which I'm best suited for. Feel free to move me elsewhere as necessary.  

I really love using Python's string methods. They apply to text based data (genetic data, book/article text data), are used for lots of little "glue" tricks (creating/extracting path information, extracting information from a well-formatted data name string), and are accessible / it's easy to see when you've made changes or acted on a string. 

I like this example that I created as a summary of day 1 of Python: 
https://christinalk.github.io/python-novice-gapminder-custom/21-end-of-day/
the punchline is that you shouldn't create a function like this, you should find a package that does it already. ;)

I also like the CO2 dataset mentioned in #14 for plotting.

**Comment by mbonsma** [comment]
I'd love to work on novice Python! I agree with @ChristinaLK, the CO2 dataset sounds great. 

In particular, I like teaching plotting (either matplotlib or seaborn), and numpy / pandas. 

I haven't worked with it myself, but after taking a look at the [Inside AirBnB dataset](http://insideairbnb.com/get-the-data.html), I'm itching to develop some exercises with it!

**Comment by joelostblom** [comment]
I'm also interested in working on intro to Python (and intro to computing/computational thinking for novices)!

Similar to @mbonsma, I enjoy teaching data wrangling and plotting. In terms of favourite examples for novices, I think it is very useful to anchor programmatic data analysis workflows in concepts that students are already familiar with. For example, describing modules as apps that need to be downloaded and installed from an app store and then opened/imported when they are to be used, and liken tab completion to clicking on a menu in a GUI-driven software to explore what functions are available in that category/module. In my qualitative assessment, examples like these appear to allow novices to construct high level representations with decreased mental load and have more energy to focus on learning the specifics of the task at hand. More specific examples in the material I linked to previously in #4)

**Comment by gvwilson** [comment]
@brandeism would like this one as well

**Comment by gvwilson** [comment]
@elliewix would like this one as well

**Comment by brandeism** [comment]
@ChristinaLK @elliewix @joelostblom @gvwilson 

For the novice Pythonistas, let's start coalescing our thoughts. As you'll see, I think unit testing/etc. should be intertwined throughout content. Comments & feedback welcomed. 

Motivation
- Why do we code? [A: discuss solving problems digitally, include short case study?]
- What are we coding? [A: algorithmic thinking and computational thinking]
- What tools are we using to code? [A: Python/R, Spyder IDE, Git, etc.; demo]  

Mechanics of Coding
- I/O basics
- Foundational structures [if/els, looping]
- Lists & dicts
- Functions
- Unit testing, validation, verification

Mechanics of Data w/ Python
- pandas [which methods do we include/exclude?]
- numpy [again, which methods do we include/exclude?]
- Unit testing, validation, verification

Exploratory Data Analysis 
[here's the meat, and there is a lot of it. Heading suggested -- add subsections as desired]
- What problem are we trying to solve? [micro hypothesis testing?]
     - Data cleanup/manipulation
     - Descriptive stats
     - Unit testing, validation, verification

- Data Analysis Intro
     - Clustering/+classification techniques
     - Linear regression
     - Indicators to cluster, classify, linear regress or something else entirely
     - Unit testing, validation, verification

- Plotting [matplotlib+other data viz tools]
     - Unit testing, validation, verification

- Re-use & Deployment Processes for Mass Distribution
[Git indoctrination: a little networking, cloud based platform and HTML understanding]

- What else?

**Comment by gvwilson** [comment]
Thanks for getting the ball rolling @brandeism - a few questions:

1.  How early can we get to plotting? People have convinced me that doing it early helps with student engagement, since they can (literally) see the value of what they're learning. If we use a library like seaborn rather than base matplotlib, can we start creating plots before we introduce control flow, complex data structures, etc.?

2. I've suggested in #75 that we teach defensive programming in the novice course and leave full-on unit testing to the intermediate material - feedback there or here from everyone would be very welcome.

3. The outline for novice R (#63) includes material on collaboration (licensing, publishing, inclusivity) - do you think that should be included in the Python course as well, and if so, can it be re-used directly across the two?

**Comment by brandeism** [comment]
@gvwilson, great questions. I don't claim to have the best answers -- only opinions so here goes!

1.  I think it's a good plan. The caveat is that some students start to *expect* immediate outcomes to *everything* that they code/run/plot. These folks then tend to get frustrated faster and it becomes harder to steer them to be patient with the big, dumb computer box. Other students can use plotting to help them understand how computers/algorithms operate. 

Limited seaborn may be worthwhile as an intro. Then, I'd suggest we take a step back and showcase matplotlib. Understanding seaborn viz can require high cognitive load for students before they are ready to digest it. 

2. I'm on the fence for this one. This is a persistent challenge for instructors of novices. The value of defensive programming is pretty clear for novices, it's easy to demonstrate its usefulness. When we emphasize defensive programming and defer unit testing, learners rely on the assertions & such later on and experience challenges in tracking down their own bugs. How about this -- toward the end of the novice learning, why don't we construct scenarios where defensive programming isn't enough? 

3. Yes and yes.

**Comment by gvwilson** [comment]
Thanks for your comments @brandeism. I've shied away from matplotlib for several years because I find it harder than all of the higher-level alternatives; I've found seaborn the least painful, but I'm sure I'm suffering from expert blind spot. There are ggplot-like libraries for Python like https://github.com/has2k1/plotnine, but as far as I can tell, they've never really built a user base :-(

Regarding testing, scenarios like that would be great - as a recovering software engineer I think unit testing is a must-have skill, but I'm struggling to convince my data science colleagues.

Thoughts from others?

**Comment by elliewix** [comment]
Here's a completely different perspective about plotting.  I like to do is make ascii bar charts when I want to provide a nugget of inspiration to continue on but not fight with third party packages or distract with something completely different.  (you can also do this with emojis, which can be used with data examples or just make it playful)

You can use it with fake data to showcase print methods, string manipulation, and loops.

``` python
In [4]: for i, observation in enumerate(data): 
   ...:     print(str(i) + ": " + observation * "X") 
   ...:                    
```
``` text                                                     
0: X
1: XXXX
2: XXXXXXX
3: XXXXXXXXXX
4: XXX
```

``` python
In [20]: for i, observation in enumerate(data): 
    ...:     print(str(i) + ": " + observation * "🐂") 
    ...:       
```
``` text                                                                 
0: 🐂
1: 🐂🐂🐂🐂
2: 🐂🐂🐂🐂🐂🐂🐂
3: 🐂🐂🐂🐂🐂🐂🐂🐂🐂🐂
4: 🐂🐂🐂
```

You can also use this as a quick and dirty method for data viz using other structures. I have something like this at the end of a lesson about gathering data from a text file, but doing proper viz is a bit out of scope.  

``` python
In [16]: from collections import Counter                                        

In [17]: phrase = "a told b and b told c"                                       

In [18]: words_count = Counter(phrase.split())                                  

In [19]: for word, count in words_count.items(): 
    ...:     print(word, (5-len(word)) * " " ,": ", count * "*") 
    ...:    
```
``` text                                                                    
a      :  *
told   :  **
b      :  **
and    :  *
c      :  *
```

**Comment by gvwilson** [comment]
I love it.

**Comment by mbonsma** [comment]
The ascii charts is an awesome idea! In general I think the sooner there is some kind of visualization, the better, but @elliewix may have the perfect compromise: no need to get bogged down in the details of plotting libraries at the very beginning, but still get some visualization opportunities early on. And if we are using interesting examples, these will be motivating even without plots.

Looking at my own past Python teaching, I have done things in about the same order as what @brandeism outlined above, so I approve of the general outline. 

As @joelostblom [suggested](https://github.com/merely-useful/merely-useful.github.io/pull/63#issuecomment-494141371) on the novice R outline, I think the **Motivation** section should also include an introduction to general computing - how do we talk to computers, why is text-based interaction helpful, etc.

**Comment by gvwilson** [comment]
People have indicated preferences; discussion about ASCII plots moved to #83.

**Comment by joelostblom** [comment]
@gvwilson @brandeism I see value in that Python and R outline aligning as much as possible, so I think it would be good to follow the [novice outline](https://github.com/merely-useful/merely-useful.github.io/blob/book/novice-goals.Rmd) as closely as possible and only depart from it when it is clearly more useful for learners to have a section explained differently in the different languages.

@elliewix  If we follow the novice outline, I think it will be easier to go straight into plotting with dedicated packages (my preference is seaborn) instead of ascii plots, since we will already be working with dataframes. If we started from more of a computer science angle and worked with small text files, I think ascii plots would fit in more naturally. So my vote would be to either not include them, include them in a later/bonus python section, or in the unix intermediate section.

@gvwilson I think plotnine should be mentioned with reference to the r section for usage.

Sorry for being late to comment.
