### ISSUE TITLE
Signup for intermediate material

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#13]
Please add a comment to this issue if you would like to work on the intermediate material (Makefiles, Unix shell, etc.).

**Comment by DamienIrving** [comment]
I have much more experience teaching intermediates as opposed to beginners, so count me in.

**Comment by katyhuff** [comment]
Ditto.

**Comment by gvwilson** [comment]
And me.

**Comment by ljdursi** [comment]
Me, too.

**Comment by gvwilson** [comment]
People have indicated preferences.
