### ISSUE TITLE
Convert column names in datasets to camel case

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#135]
As per meeting. So they immediately work with clean data.

Later we could get the learners to tidy up a messier more realistic dataset.

**Comment by joelostblom** [comment]
`snake_case` right?

**Comment by cwickham** [comment]
@lwjohnst86 Would you mind if I took this on?  I have some other data I'd like to add related to the `dog_licenses` and it seems like I might as well fix this at the same time.

**Comment by lwjohnst86** [comment]
@cwickham for sure! here's the code in #144 I started to work on related to it
