### ISSUE TITLE
Proposal: Use Github Project Boards to keep track of tasks and progress

### ISSUE THREAD

**Issue by ljdursi** [merely-useful/merely-useful.github.io#139]
## Proposal

I propose that we begin using [GitHub Project Boards](https://help.github.com/en/articles/about-project-boards) to provide at-a-glance overviews of the tasks currently in progress, blocked, unassigned, and waiting for reviews.  For concreteness, this proposal would have us:

* Create two project boards, one for content (the sections themselves, the data sets being used for the sections, etc) and one for infrastructure
* Have columns in each board for "unassigned", "blocked", "in progress", "ready for review", "ready to merge", and "merged".
* Create a number of unassigned issues for sections of content that are not currently being worked on

## Background

We currently have 14 team members and 44 open issues; in addition, there are unassigned sections that do not yet have issues created.   Getting a sense of what is currently being done by the other team members and what remains to be done involves skimming through the issues and clicking on them one at a time, and we don't have any way of quickly finding out what is not being worked on that does need to be.

## Pros and Cons

**Pro:**
-   Makes it easier to get a sense of the project as a whole
-   Doesn't require the use of a new tool/website; it's all part of Github

**Con:**
-   Requires team members to update the project board when an item changes status
-   Requires team members to add new issues to one of the boards
-   Increases the number of open issues

## Alternatives

Alternatives include (1) using other tools instead, or (2) not using anything.

### Other tools

For other tools, there are no shortage of cheap/free other tools for keeping track of tasks.  Asana and Trello are tools that several teams I know swear by.  I'd argue that for our purposes we don't need anything particularly full-featured, and having it integrated into where the work is being done is useful; having said that, several of those tools integrate with slack and that would be helpful too.

### Leave it as is

Otherwise we could just use github issues as currently; if we are to do that I'd advocate at least for creating issues for all the sections that aren't currently assigned to everyone so we can see what is not yet being worked on in addition to what is happening on the tasks that are; and add labels to indicate status.

**Comment by lwjohnst86** [comment]
100% agree with this. Question, what do you mean by "blocked"?

**Comment by lwjohnst86** [comment]
And I assume the "proposals" and "discussions" will be under the appropriate Project Boards? (e.g. I feel this proposal would fall under infrastructure?)

I volunteer for managing the infrastructure Board if this gets implemented.

**Comment by ljdursi** [comment]
Blocked would mean assigned but it can't be worked on/worked on further until something it depends on is completed; might not be super relevant for this project at least at this stage.

**Comment by lwjohnst86** [comment]
Agreed as per the meeting :) We'll have boards set up soon
