### ISSUE TITLE
Revise section on managing backlog

### ISSUE THREAD

**Issue by ljdursi** [merely-useful/merely-useful.github.io#148]
Revise `backlog.Rmd`:

* Exercises
* Concept map
* Github boards?

**Comment by DamienIrving** [comment]
At the [10 September meeting](https://github.com/merely-useful/merely-useful.github.io/wiki/Meeting-agenda-2019-09-10) @k8hertweck volunteered to look over the project management content (which also includes #161 and #162) and @elliewix mentioned that she might have some existing materials that could be useful.

Check out [`rse-goals.md`](https://github.com/merely-useful/merely-useful.github.io/blob/book/rse-goals.md) to see how the project management content fits within the rest of the intermediate course.

**Comment by k8hertweck** [comment]
I'd be amenable to closing this, as the first draft is up and current concerns are being documented in #278
