### ISSUE TITLE
Revise section on configuration of software

### ISSUE THREAD

**Issue by ljdursi** [merely-useful/merely-useful.github.io#156]
Revise `configure.Rmd`:

- [ ] Exercises
- [ ] Is an R section needed?

**Comment by DamienIrving** [comment]
See #223

**Comment by DamienIrving** [comment]
As it stands, `configure.Rmd` covers how to write a python script (using argparse) and then looks at (and implements) overlay configuration. 

I was initially assigned to this issue and started working on an update to `configure.Rmd` but wasn't sure how relevant the overlay configuration content is for our audience. At the [meeting on 8 October](https://github.com/merely-useful/merely-useful.github.io/wiki/Meeting-agenda-2019-10-08) we decided to move `configure.Rmd` to `configure.md` for now and to discuss further how best to teach configuration (if at all). The beginnings of that discussion at at #223 but we should continue the discussion here.

(Python scripting will now be a separate chapter.)

**Comment by gvwilson** [comment]
@DamienIrving closing snce we have remove configure.Rmd
