### ISSUE TITLE
Revise documentation section

### ISSUE THREAD

**Issue by ljdursi** [merely-useful/merely-useful.github.io#158]
- [ ] Exercises
- [ ] Concept map

**Comment by DamienIrving** [comment]
Does documentation belong in the novice or intermediate course? Or split between the two? (If the latter, which aspects are novice and which intermediate.) 

At the moment, much of `docs.Rmd` could be covered with docstrings are introduced in novice python...

**Comment by ChristinaLK** [comment]
I feel like it's good to give at least a little about documentation to novices. 

What would have been useful to me starting out: 
- knowing about docstrings (which I DID know about)
- understanding conventions for writing up arguments/docstrings
- what kind of comments are helpful or not (i.e., when is it better to have clear function names than to use loads of comments)
- should always create a README in a project folder --> could also go in the project organization section?
- *simple* README outline (purpose, dependencies, usage?) --> ditto to above.
