### ISSUE TITLE
Revise project structure section

### ISSUE THREAD

**Issue by ljdursi** [merely-useful/merely-useful.github.io#160]
Revise `project.Rmd`

- [ ] Exercises
- [ ] Concept map

**Comment by DamienIrving** [comment]
At the 10 September meeting @cwickham volunteered to look over the project structure content and @elliewix mentioned that she might have some existing materials that could be useful.

**Comment by cwickham** [comment]
@elliewix, it sounded like you don't have too much time right now...so how about you dump your materials as a PR on [my `rse-project` branch](https://github.com/cwickham/merely-useful.github.io/tree/rse-project) and I'll take a go a integrating with what is currently in `rse-project.Rmd`?

@k8hertweck, did you also have some materials on this topic?

**Comment by ChristinaLK** [comment]
I can help review this.

**Comment by elliewix** [comment]
I added what I sent to Kate in the bottom of that as a PR. I tried to indicate where good activities would be.  Umm... I clicked the PR option during commit but it looks like it committed to master?? :-\ I stand confused and apologetic.

**Comment by cwickham** [comment]
I'm a bit confused too...I guess I wouldn't have expected you to be able to commit directly to my fork...but this workflow is still a bit new to me.   

Anyway, I have your stuff, thanks! I'll take a crack at incorporating it.
