### ISSUE TITLE
Compare with yet another book on data science

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#165]
https://www.anotherbookondatascience.com/index.html - see how our stuff compares

**Comment by DamienIrving** [comment]
The thing that separates Software Carpentry from everything else out there (I think - happy to be corrected) is the focus on programming best practice (modular code, defensive programming, building reproducible workflows using command line programs and make, etc). That book you've linked to and so many others teach you basic Python and R syntax and how to do stuff with specific libraries, but IMHO that's stuff you can pick up from a Google search. The Software Carpentry best practice stuff is what the matplotlib gallery code snippets and Google searches don't tell you - that's our point of difference (and will hopefully shine through in Merely Useful).

**Comment by ChristinaLK** [comment]
big +100 to Damien's comments - you can look up a tutorial on webscraping, but it's not going to tell you how to set up a project directory, develop your code w/ version control, create functions, etc.

**Comment by DamienIrving** [comment]
Looks like Another Book on Data Science will be published as [A Tour of Data Science](https://www.routledge.com/A-Tour-of-Data-Science-Learn-R-and-Python-in-Parallel/Zhang/p/book/9780367895860) in December 2020.
