### ISSUE TITLE
Preserve filenames for chapters

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#17]
Bookdown creates a filename from the title of the chapter, rather than by using the stem of the source filename, e.g., `automate.Rmd` becomes `docs/automating-analyses.html`. I would prefer to preserve the source filenames in order to keep URLs short (and stable if we rename chapters).

**Comment by lwjohnst86** [comment]
This is achieved through the use of `{#chapter-name-you-desire}` at the first `# Chapter Header`. In the intermediate source files, they already have `{#s:...}`. In this case, we don't need the `s:`.

**Comment by gvwilson** [comment]
Awesome - I'll make that change later today.
