### ISSUE TITLE
Discussion: What is our reccomended Python installation procedure and package manager

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#173]
I find Anaconda + conda to be the most straightforward and it also allows for easy creation of virtual envs. pyenv and pip would be the first alternative that comes to mind.

**Comment by mbonsma** [comment]
My vote would also be for Anaconda, but it somewhat depends on where the [publishing](https://github.com/merely-useful/merely-useful.github.io/issues/177) discussion takes us - if we decide to include a lesson on Jupyter, then I would vote even more strongly for Anaconda, but if we use something else then it might be worth going more lightweight.

**Comment by ChristinaLK** [comment]
I am a +1 for Anaconda.

**Comment by lwjohnst86** [comment]
We'll stick with (go with) Anaconda, seems that's the most popular choice.
