### ISSUE TITLE
Move data over so it is available at `data` location on website

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#179]
As per discussions in #137, converting the data into an R package to be easily accessed and used would probably really help smooth things over when learners are going over the material. (e.g. no need to worry about paths, dataset location, etc).

Once we get more into editing and polishing up we can work towards package conversion, which shouldn't be too too difficult.

**Comment by joelostblom** [comment]
I am a bit split on this, isn't it good that we talk about what data is and how the dataset looks before getting into working with it? So the students would be familiar the contents and that it is stored in a CSV file. If we host the dataset and it is loaded it from a URL, there is not need to worry about the dataset location either. Wouldn't this approach be easier to understand for students than comprehending how the data got into the form of an R-package? And it would be a real-life example of how data is loaded in R/Python (which I think is an asset as long as it does not complicate the procedure which I don't think it does here). Just some thoughts, discuss at the meeting?

**Comment by cwickham** [comment]
I think it may be nice to be able to use both approaches.  To get students up and running with some plotting or manipulation with minimal setup: load data from a package.  To illustrate examples of data import, give a more realistic process etc.: read data from a URL.

Is there any benefit to having the URL reflect the location of the book, as opposed to the github repo?  E.g. right now this works:
```r
sites <- read_csv("https://raw.githubusercontent.com/merely-useful/merely-useful.github.io/book/data/site.csv")
```

But it might be nice to have this:
```r
sites <- read_csv("https://merely-useful.github.io/data/site.csv")
```

@lwjohnst86, that becomes an infrastructure change, but perhaps a straightforward one?

**Comment by lwjohnst86** [comment]
@cwickham yes, that is quite easy to implement. Given that this would impact both R and Python users, I'll switch this issue over so the data is accessible on the website.
