### ISSUE TITLE
Get permission to use Jeff Allen's nice piping example

### ISSUE THREAD

**Issue by cwickham** [merely-useful/merely-useful.github.io#184]
I really like this suggestion below from Joel.  @gvwilson, could you ping Jeff and see if he would be OK with us re-using it?

---

I don't think the benefits of piping are immediately obvious with simple examples. Could you illustrate the improved readability with a toy sentence to point out that it really helps readability notably? Something like this:

```
tumble_after(
    broke(
        fell_down(
            fetch(went_up(jack_jill, "hill"), "water"),
            jack),
        "crown"),
    "jill"
)
```

becomes

```
jack_jill %>%
    went_up("hill") %>%
    fetch("water") %>%
    fell_down("jack") %>%
    broke("crown") %>%
    tumble_after("jill")
```

from trestletech.com/wp-content/uploads/2015/07/dplyr.pdf

_Originally posted by @joelostblom in https://github.com/merely-useful/merely-useful.github.io/diffs/4_

**Comment by gvwilson** [comment]
pinged...

**Comment by gvwilson** [comment]
Jeff says "yes we can use it". cc @cwickham
