### ISSUE TITLE
Raw material for Docker

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#189]
If we decide we need to... http://ropenscilabs.github.io/r-docker-tutorial/

**Comment by ChristinaLK** [comment]
https://uw-madison-datascience.github.io/docker-introduction/

**Comment by ljdursi** [comment]
If the intermediate material was to culminate in something where there was both a python tool and an R tool working together, having  a docker section for "packaging" the multi-tool project and having it up on quay.io or docker hub would be really nice.
