### ISSUE TITLE
Discussion: Should we use type hints in Python function signatures?

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#196]
I have not been not including the [Python type hints](https://docs.python.org/3/library/typing.html) in function signatures. I guess including them would technically be best practice since it allows IDEs to autodetect easier, but I find that it can get messy quickly when there are many parameters, default arguments, and multiple types for a parameter. I believe many IDEs can read and richly render numpy doscstring and this is my preferred way of annotating functions.

Thoughts? Strong feelings?

**Comment by gvwilson** [comment]
:-1: on type hints - only a small minority of Python programmers use them, so most of the code our learners see won't have them.

**Comment by ChristinaLK** [comment]
Agree w/ Greg: my first response to this was "I've never heard of these."

**Comment by joelostblom** [comment]
Good, then I'll close this. Anyone who feels strongly the other way can reopen or bring for discussion at the next meeting.
