### ISSUE TITLE
Discussion: modularity of each section 

### ISSUE THREAD

**Issue by SaraMati** [merely-useful/merely-useful.github.io#199]
It would be nice if each chapter's scripts be standalone, or to make it easier for people to run the scripts if they start from a certain chapter (example: the Python data manipulation sector starts with 'import' numpy. we can refer them to the section on making an environment  and install packages etc., or start the script from installation point) 

so to discuss 
Requirements for modularity:
- links to pre-requisite concepts
- links to setup and package installation instructions
- what other things they need for making the scripts of that chapter standalone?

**Comment by lwjohnst86** [comment]
Maybe relevant: https://yihui.name/en/2018/09/code-appendix/
