### ISSUE TITLE
Proposal: Write in second person ("you")

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#202]
## Proposal

Address the learner directly by using using second person ("you") when writing. I summarize (and paste from) what was said in issue #175 below.

## Background

We want to be consistent in the writing between chapters. Deciding whether to write in first ("we") or second ("you") person now can reduce editing later.

## Pros and Cons

**Pro:**
- Sounds more engaging and encouraging ("you can, and should, go try this now")
- The student is in the driver's seat

**Con:**
- Might sound too instructional ("you do this, you do that").

## Alternatives

Writing "we" could convey a safe/familiar tone and the feeling that problems are solved  together with the author as a team. However, it might also sound non-personal or even preachy (as if "we" are not really doing anything and the author should just have use "I" instead). The narrator is in the driver's seat.

**Comment by lwjohnst86** [comment]
Votes were pretty mixed. Some of us use "we" and also "you" depending on the context. We'll go with however the author of the chapter feels comfortable, and fix it at editing phase.
