### ISSUE TITLE
Discussion: One thing people really need to know that we haven't covered

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#207]
As per our meeting discussion, @gvwilson asked: "what's the one thing that people really need to know that we haven't planned to cover?" (see [minutes](https://github.com/merely-useful/merely-useful.github.io/wiki/Meeting-agenda-2019-09-10) for more details).

**Comment by gvwilson** [comment]
I think the sections on publishing and data inventory were two big gaps that are now being filled. I *don't* think we need anything on parallelism, job control, or performance tuning. I still think about regular expressions, but the one that sticks with me most is "how to use your editor efficiently". It seems like a small thing, but it's one of the differences I see between those who can program quickly and those who can't.

**Comment by ChristinaLK** [comment]
I agree re: the editor. I was watching someone who has learned the command line shortcuts beyond CTRL-A and CTRL-E and was like...this would help me. Same applies to editor. 

The *only* piece that I think is important for parallelism is designing your code in a modular way, so that it's easy to parallelize a chunk of it if needed.

**Comment by lwjohnst86** [comment]
I can't recall if this is in there, but learning how to learn/learning how to use StackOverflow or Google to solve the problem you may have. But this is tricky to teach I feel.

**Comment by ChristinaLK** [comment]
I put some of that into the "getting started" chapter for python: https://merely-useful.github.io/py/py-getting-started.html#py-getting-started-web-help

**Comment by k8hertweck** [comment]
I would strongly support more exercises interspersed throughout the material that reinforce how to properly phrase a question for Googling. I think this is a skill that develops along with someone's mental model of how terminology and practice come into shape, and extra examples are really useful, especially in the first 25% of the material.

**Comment by elliewix** [comment]
To @k8hertweck's comment, I agree and have a quick tutorial that could be adapted to this that's based on a study about how novices google

**Comment by joelostblom** [comment]
A few things on my mind, maybe this is somewhat covered in sections under development.

- Project structure - sound folder organization and principles, e.g. https://drivendata.github.io/cookiecutter-data-science/
- When to modularize code and how to effectively work with your own package in a data analysis pipeline
    - In addition to what we have on package and function development, I am thinking about things like when to break logical segments into separate function, how to install editable packages, and how to automatically update packages in the IDE (e.g. autoload magic in jupyter notebooks).
- Data narrative - learning basics around how to tell a story with data.
- Create a skeleton for analysis with what is important to always include versus what is data dependent (I haven't looked for a specific guide for this, but a general skeleton for a workflow that is more succinct than the lectures and references where to read more, e.g. 1. look for missing data, 2. check column data types, 3. make an overview plot, -1 include version numbers of packages so others can reproduce, etc)

**Comment by joelostblom** [comment]
@lwjohnst86 Regarding how to use SO, I have [this section](https://github.com/merely-useful/merely-useful.github.io/blob/book/py-development.Rmd#L500-L526) in py-dev.

**Comment by joelostblom** [comment]
@gvwilson I added some editor tips in #225 , is this around the level you were thinking or should it be more advanced?
