### ISSUE TITLE
Do not include questions, objectives, and key points sub-headings in ToC

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#21]
1. Every chapter has a level-2 heading `Questions` and another `Key Points` - these shouldn't show up in the ToC.
2. The level-2 headings in `questions.Rmd`, `objectives.Rmd`, and `keypoints.Rmd` repeat the chapter titles - they should not be included in the ToC.

**Comment by lwjohnst86** [comment]
I'll look into it. I have an idea of a way to work around that, but I want to test it out first if it works.
