### ISSUE TITLE
Proposal: move discussion of style to novice material

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#210]
## Proposal

Move `style.Rmd` to the novice material.

## Background

`style.Rmd` is currently in the RSE material, but we can and should teach good coding style earlier.

## Pros and Cons

**Pro:**
-   We should teach good programming style as early as possible.
-   Nothing in the material requires in-depth understanding of Python or R.
-   Load balancing (evens out sizes of volumes).

**Con:**
-   Will need to do for both Python ~~and R~~ (*Note*: Already done in r-reproducibility).

## Alternatives

NA.

**Comment by lwjohnst86** [comment]
I think this is a good idea, though I've already done a big section on style in the r-reproducibility section. So it would have to be done for the Python. I don't know how its like in Python, but the `styler` package makes it super easy to adhere to the style guide in an automated way.

**Comment by lwjohnst86** [comment]
The bit about code review would be very useful in the RSE, but not really the novice material though

**Comment by lwjohnst86** [comment]
Passes. Move into novice.
