### ISSUE TITLE
Auto-generate a list of figures and a list of tables

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#22]
As the subject line says, it would be nice to have a list of figures (as a page) and a list of tables (as a page).

**Comment by lwjohnst86** [comment]
I don't believe this can be done with the `gitbook` output, but [can be done](https://bookdown.org/yihui/bookdown/publishers.html) in the PDF output. Will that be good enough?

**Comment by gvwilson** [comment]
I'm a big fan of consistency - leave this one open for now and hopefully someone will add this feature to bookdown before we ship?
