### ISSUE TITLE
rse-bash suggestions

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#220]
@gwilson Aside from my suggested changes in the PR #219 , here are a few comments for you to do with as you see fit.

- [ ] Remove `$` code prefix everywhere
    - This will make code easier to copy
    - We don't include the prompt character for either Python or R.
- [ ] Where do we instruct readers to download the folders and follow the setup
      instructions for the carpentry bash lecture?
- [ ] Should we mention `.basrhc` instead of `.bash_profile` as an example of
  a hidden file since we mention that this is the config file, but I persume
  that we will modify `bashrc` if we are to show how to configure bash?
  I didn't make the changes because I wasn't sure if macOS for some reason did
  not always have `.bashrc`,but `bash_profile` instead. - 
- [ ] I am used to writing `n`/`N` instead of `N`/`Shift+N`, but maybe that's
  a vim thing.

Things that I did not see mention of that could be useful
- &, ^Z, and fg.
- sudo
- shebang line
- aliases
- bashrc config
- the escape character (\\)
- {a,b} for matching either or
- single vs double quotes

**Comment by ChristinaLK** [comment]
+1 to single vs double quotes -- it seems picky, but when you use variables it really does matter. 

+1 also to shebang line -- generally useful and also good to clarify that it's not a comment.

**Comment by gvwilson** [comment]
Thanks for the feedback:

- Remove `$` for consistency: yup.
- Download instructions: web page rather than in the book, because instructions will change more frequently than content (particularly during first contact with users).
- Single quotes: check.
- shebang: only useful if we teach permissions, which we don't.
- sudo, aliases, etc.: sure, as long as you can tell me what we take out to make room, because this is already the longest chapter in the whole series by a factor of 2.

**Comment by joelostblom** [comment]
> +1 to single vs double quotes -- it seems picky, but when you use variables it really does matter.

Yes, especially since it does not matter in R and Python, I think it is important to just mention this in a short sentence, possibly with a link to a more complete explanation of variable expansion. 

> sudo, aliases, etc.: sure, as long as you can tell me what we take out to make room, because this is already the longest chapter in the whole series by a factor of 2.

Point well taken. The reason I bring up aliases and bashrc is that I want to mitigate the annoyance that can be felt from having to type the same flag every time a command is used (We also mention "the shell's default settings" in the section without explaining what that means). I think this is important and powerful enough to justify a few sentence along the lines of:

> "Some option are so useful that you want to apply them every time you use a command. For example, `rm -Iv` will make sure that you are prompted if you accidentally try to delete too many files and the path of each deleted file is printed to the screen. To save us some typing, we can make the `rm` command an alias (a nickname) for `rm -Iv` by typing `alias rm="rm -Iv"`. To make this change persistent between reboots, we can append the line to `~/.bashrc` (which might already have some default aliases). You can read more about aliases and configuring your default bash settings [here](insert suitable link).

A good candidate for taking out could be quoted section talking about `!!` usage and similar  variants.

**Comment by joelostblom** [comment]
Another thing that would shorten this chapter is if (part of) the intro is adapted as a general intro to programming instead of the shell specifically and moved to an intro section of the novice material (where there should be some kind of intro to computers, maybe there is and I looked in the wrong place).

**Comment by ChristinaLK** [comment]
@joelostblom having just read @DamienIrving's chapter on configuration...that could be an alternate location for bashrc/bashprofile and aliases...

**Comment by joelostblom** [comment]
@ChristinaLK Good point! I agree that sounds like a good location.
