### ISSUE TITLE
Discussion: Unify narrative between languages in the novice material

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#226]
I think it would eventually be a good idea to unify the narrative between the Python and R section to be as close as possible without impairing the learning experience in the respective language. This might also save time with the remaining sections, since they can be developed in one language and then adapted to fit the other language (and ensure a thorough review and updates "upstream" during the adaption).

What do you think, is this unnecessary or beneficial, time consuming or time saving?

**Comment by lwjohnst86** [comment]
It might be time-saving, but there are definite major differences between using R vs Python that I don't think would be easily resolvable with a shared text. We could explore it though!

**Comment by DamienIrving** [comment]
I think the broad narrative could/should be the same (e.g. starting with X dataset we want to plot A, B and C interesting features of the data). The concepts introduced along the way to get from the original data to the interesting plots will be different between the languages, which is fine.

**Comment by joelostblom** [comment]
> I think the broad narrative could/should be the same (e.g. starting with X dataset we want to plot A, B and C interesting features of the data).

:+1:

> The concepts introduced along the way to get from the original data to the interesting plots will be different between the languages, which is fine.

I would go one step further and say that the concepts should be the same but their implementation differ depending on language For example, a common narrative carries us to a section where we want to summarize/aggregate data, we introduce the concept of split-apply-combine the same way for both books, but its implementation will differ between R and Python.

I could see the benefit of using slightly different wording between languages to mach their respective function names, e.g. talking about how to summarize versus how to aggregate data. Beyond that, I don't see any benefit in diverging narratives or concepts, unless something is done according to a radically different philosophy rather than different ways of achieving the same end goal (nothing comes to mind, or possibly `purr` I guess but would have to think more about it)
