### ISSUE TITLE
Automatically include the words 'Chapter', 'Section', 'Figure', etc. in cross-references

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#23]
The `\@ref(...)` syntax in bookdown inserts the appropriate figure or section number, but does *not* include the word `Chapter`, `Section`, or `Figure` - it would be very handy if this was an option.

**Comment by lwjohnst86** [comment]
This I think is a shortcoming of pandoc. I don't believe that it's possible at this point to include those words in the reference.

**Comment by lwjohnst86** [comment]
Can't be done right now. Closing (will add "on hold" label for easier later reference).
