### ISSUE TITLE
Discussion: Linkages between RSE chapters 

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/merely-useful.github.io#240]
As it stands right now, there is very little relationship between the data, code and/or narrative used from one RSE chapter to the next:  
* **Bash shell**: Uses a `climate-data` directory
* **Git**: Frances and her colleague Jean Jennings write a history of the ENIAC project
* **Python scripting**: Yet to be decided (#232) 
* **Automation**: The distribution of word frequencies in classic English novels is analyzed using two pre-prepared scripts (`countwords.py` and `collate.py`)
* **Packaging**: Develops some "Zipf code" which builds on the word frequency data and narrative (but not code) from the automation chapter

The other RSE chapters (please correct me if I'm wrong) don't really involve a specific dataset or analysis narrative and don't use any code that was developed in a previous chapter or used again in a subsequent chapter.

I'm opening this issue to discuss whether or not we want any linkages between the RSE chapters. If we do, then what should they be? And should they also link to data, code and/or narratives used in the novice chapters?

For instance, the bash shell chapter could use a directory that has text files for the classic english novels in it, the python scripting chapter could then write the `countwords.py` and `collate.py` scripts, the automation chapter could use those scripts in a workflow, and the packaging chapter could package up the scripts for use by others. Or, we could simply decide not to try and maintain links between chapters.

**Comment by joelostblom** [comment]
I would also prefer a linked narrative and think this would be easier for readers to follow. Being familiar with the data would also (I imagine) reduce cognitive load when new concepts are introduced (versus having to learn new concepts and new data). 

I think the story we tell is really important to keep learners engaged and facilitate for them as much as possible (or avoid confusing them, whichever wording you prefer). That is why I opened #226 also, I think we can put more effort into one great narrative if is similar across as many chapters as possible.

As a caveat it seems appropriate to mention that I have not experience in teaching with a disjoint narrative, so don't have any evidence for is leading to a subpar learning experience, maybe it could be refreshing to not see the same data all the time?

**Comment by elliewix** [comment]
Lots of positive discussion here.

We should come up with a coherent starting narrative, then come up with the end game code for each of the chapters.
Once we have that written the group doing the rewrites should go back through the plan and revisit the narrative based on how the programs were actually implemented.
After that we can slice out the relevant concepts from each and start assigning writing tasks.

**Comment by SaraMati** [comment]
I think this also addresses this [issue](https://github.com/merely-useful/merely-useful.github.io/issues/240): if the narrative is unified, only a link to pre-requisite chapters suffices. each chapter has standalone code that completes the overall picture. #199

**Comment by DamienIrving** [comment]
I've started thinking about what the narrative might be and the practicalities of weaving it through the existing chapters. Check it out (and please comment) at #283.

**Comment by DamienIrving** [comment]
Now that the code for the Zipfs Law narrative has been written (#293) we need to update all the RSE Python chapters accordingly (see `py-rse/narrative.md` for details of what needs to be updated). I've started to assign people to different chapters below - feel free to change what I've done, as I'm really just guessing to get the conversation started.

Chapter 1:  Introduction [`py-rse-index.Rmd`] @DamienIrving
Chapter 2:  Basics of the unix shell [`py-rse/bash-basics.Rmd`]
Chapter 3:  Going further with the unix shell [`py-rse/bash-advanced.Rmd`]
Chapter 4:  Command line programs [`py-rse/py-scripting.Rmd`] @DamienIrving
Chapter 5:  Git at the command line [`py-rse/git-cmdline.Rmd`]
Chapter 6:  Advanced Git [`py-rse/git-advanced.Rmd`]
Chapter 7:  Automating Analyses [`py-rse/automate.Rmd`]
Chapter 8:  Program configuration [`py-rse/configuration.Rmd`] @DamienIrving
Chapter 9:  Error handling [`py-rse/errors.Rmd`]
Chapter 10: Working in teams [`py-rse/teams.Rmd`] @k8hertweck
Chapter 11: Code style, review and refactor [`py-rse/style.Rmd`]
Chapter 12: Project structure [`py-rse/project.Rmd`] @cwickham
Chapter 13: Correctness [`py-rse/correct.Rmd`] 
Chapter 14: Continuous integration [`py-rse/ci.Rmd`] @lwjohnst86
Chapter 15: Python packaging [`py-rse/package-py.Rmd`] @lwjohnst86
Chapter 16: Publishing [`py-rse/publish.Rmd`] @DamienIrving

**Comment by joelostblom** [comment]
I added myself to automation and error handling. I haven't read through those previously so I can do a general review. Open to other suggestions as well.

**Comment by cwickham** [comment]
Happy to do Project Structure although maybe someone with more experience documenting data might be more appropriate? @elliewix ?

I'll take a crack at Git at the command line.

**Comment by elliewix** [comment]
Happy to do project structure!

**Comment by DamienIrving** [comment]
@lwjohnst86 - You name is against Chapter 14 (continuous integration), but that actually depends on Chapter 13 (correctness) because the CI will implement the tests written in Chapter 13. Do you want to tackle Chapter 13, or would you like me to do it? (I can make that the first chapter I tackle.)

**Comment by lwjohnst86** [comment]
@DamienIrving I can do correctness instead of python packaging. I was actually just thinking that during the meeting.

**Comment by DamienIrving** [comment]
@joelostblom Thanks for offering to do the error handling chapter. Of all the chapters, it's probably the only one that I'm still wondering whether we actually need, so it would be good to get your opinion on that.

Also, would you be comfortable taking on the python packaging chapter?

**Comment by joelostblom** [comment]
@DamienIrving I will keep that in mind when reviewing the error handling chapter!

I'm a bit overloaded with other tasks atm, so I will likely not be able to review python packaging before the next meeting. I could look at it later though if we are ok leaving it for a bit longer (or if someone else has time before the next meeting).

**Comment by DamienIrving** [comment]
@joelostblom Leaving it for a bit longer is no problem, particularly as it's the second to last chapter. Happy for others to jump in if I'm wrong, but now that Jonathan Dursi (who wrote the original packaging chapter) isn't working on the project I'm not sure that we've got too many others with experience with python packaging on the team? (I've written very basic packages in the past but not recently.)

**Comment by joelostblom** [comment]
@DamienIrving Are you planning to move [this entire chunk](https://github.com/merely-useful/merely-useful.github.io/blob/book/py-rse/automate.Rmd#L23-L92) from automate to the intro files? And instead of starting point referring to the the structure as the goal? If so, I can just reference that section from automate. Or do you think it makes more sense to keep the file structure in automate and just move the prior intro sections?

**Comment by DamienIrving** [comment]
@joelostblom Yep. All the introductory comments about Zipf's Law and what we're going to be analyzing / looking for will be moved to the intro chapter, so you can remove all of it from the automation chapter.

**Comment by k8hertweck** [comment]
Please see [`narrative.md`](https://github.com/merely-useful/merely-useful.github.io/blob/book/py-rse/narrative.md) for awesome explanations about what needs to be changed in each chapter!

**Comment by elliewix** [comment]
Sorry all, I've been fighting pneumonia for a week and haven't been able to work on the project section rewrite. I'm hoping to be back on things next week.

**Comment by gvwilson** [comment]
Can this one now be closed?
