### ISSUE TITLE
Add heuristics and workflow advice for when to modularize code

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#241]
In the py-dev chapter, I have written about [functions](https://github.com/merely-useful/merely-useful.github.io/blob/book/py-development.Rmd#L8) and [packages](https://github.com/merely-useful/merely-useful.github.io/blob/book/py-development.Rmd#L339). I think this chapter can be reorganized and a few lines can be added to explain criteria for when to break out code into functions and briefly also packages and then point to RSE for more details around creating packages. 

@elliewix Thank you for offering to add the material you have already. Do you think it would fit well in this chapter to extend or bridge the section I mentioned above? As I said, we can reorganize as we see fit, I just followed the order in the outline file to make sure I covered all the bullets.

@DamienIrving Then for the packaging section, you could maybe briefly repeat when we modularize into functions and packages and go into details about packages. Just to make sure, [is this the file](https://github.com/merely-useful/merely-useful.github.io/blob/book/rse-package-py.Rmd) where the material would go? [This blog post](https://florianwilhelm.info/2018/11/working_efficiently_with_jupyter_lab/) talks about some of the principles around extracting code from the notebook into modules (up until section 2-3), which is largely what I am thinking about (have an edible packages and use `%autoreload 2`)

---

Somewhat of and aside, do we want to make a difference between a local package and a package for distribution? In my workflow, I rarely have .py files in the same directory as my notebooks, instead I create a local editable package so that the notebook imports are tidier and don't need to change if I decide to move things around. To be clear the diff would be that I can write

`from mypkg.myfile import myfunc`

instead of 

`from myfile import myfunc` (and then have to change this if I move files around or want to create a package).

This is maybe not a major point, but I wanted to mention it so it is clear how I am thinking about this and point out that local packages like these don't require all the things a public package requires (readme, contrib, coc, version etc), it's more like an organized dump of functions from notebooks (often multiple in the same project). The more I write, the more this sounds like something that should go into RSE instead of novice...

**Comment by elliewix** [comment]
I reviewed the chapter and have made additions.  I was thinking more about adding things about creating your own custom function file, but I see that's pretty well covered in another chapter.  I'll be submitting a PR with my proposed additions. Feel free to accept/squash per your vision.

**Comment by elliewix** [comment]
OK I have made this thing, https://github.com/merely-useful/merely-useful.github.io/pull/273, which may or may not have been done right.
