### ISSUE TITLE
Build multiple books in a single repository

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#25]
This may require one sub-directory per book, since it doesn't look like multiple `_bookdown.yml` files in a single directory are happy.

**Comment by lwjohnst86** [comment]
This was something I was actually thinking about doing. If I can get the CI working correctly, I could get it to push each book into it's own repo to be hosted online there. We could then set those repos as read only or something so other users don't fork them and submit PRs through them. Is that possible you think?

**Comment by lwjohnst86** [comment]
@gvwilson do you want me to build to this repo's gh-pages or to build to the `still-magic` for the bookdown branch? I don't have admin rights on this repo to test whether the CI to build the output works or not.

**Comment by gvwilson** [comment]
1. You should have admin rights: I gave them to the whole team. I'll dig...
2. I'd like to merge `bookdown` into `master` as soon as possible - as long as we can preview locally, I'm not fussed about whether we build into `gh-pages`, into the `docs` folder, etc.
Thanks!
