### ISSUE TITLE
Force bookdown to copy extra files into docs directory

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#26]
Extra files, such as the contents of the `./src` directory or any images in the root of `./figures`, should be copied into `docs`. This can be done via the Makefile, but if there's a way to get bookdown to do it, that might be cleaner.

**Comment by lwjohnst86** [comment]
You mean the pratchett image? Will that be the cover or logo? I don't see it being linked to in any files. I think if it is linked it will be moved over.

**Comment by lwjohnst86** [comment]
What's the rationale for being moved over? I see that, ie. this:

```
<!-- src="logging/ask_permission_not_forgiveness.py" -->
``` 

Is included as a comment in line 271 of `logging.Rmd`. Do you want it accessible via the gitbook?

**Comment by gvwilson** [comment]
1. I haven't approached the BBC for permission to use the Pratchett image, so best to leave it unlinked for now - the question was more generally about how to get bookdown to move over "extra" files that we may want to refer to.
2. The HTML comments with `src="path"` are left over from the earlier (Jekyll) version of these notes - we need to decide how to add file references so that if people want to click and download the source for an example, they can do that without copying and pasting. Putting the file path into a `{python...}` block header failed, so I put 'em all in comments for now.

**Comment by lwjohnst86** [comment]
I think this could be done by simply copying the folders over via shell commands in the makefile.

**Comment by gvwilson** [comment]
I'm good with that - I just thought there might be some bookdown magic, but I'm all in favor of things I actually understand :-) Assign this back to me and I'll tackle it?

**Comment by gvwilson** [comment]
@lwjohnst86 Can this one now be closed? (Looks like the Makefile is doing what we want.)
