### ISSUE TITLE
Reorganize material in rse-project, rse-publish, and rse-teams

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#278]
There is a lot of duplication in `rse-project.Rmd`, `rse-publish.Rmd`, and `rse-teams.Rmd`, and the order is jumbled: it needs a high-level reorganization.

**Comment by elliewix** [comment]
I have a note to look at several of these chapters with some commentary, and can take a look at these three. This can be assigned to me.

**Comment by k8hertweck** [comment]
This is related to #245 that @SaraMati and I are working on; we'll do our best to get that tidied up ASAP

**Comment by elliewix** [comment]
Let me know when you're done with that and I'll take a look.  Note that I'm off tomorrow and won't be able to look at this until Monday.

**Comment by gvwilson** [comment]
Any updates on whether this is mergeable? thx - G

**Comment by k8hertweck** [comment]
Until I know how to update the relevant files (following the split of rse into r and python), here are my thoughts on what needs to happen for this issue:

- My current vision for splitting this content includes:
  - `project.Rmd` is about planning, directory structure, files common to many projects, and documenting all of the above
  - `teams.Rmd` is about the project as it is in process, and tools to assist working with people and tasks
  - `publish.Rmd` is about creating static artifacts, like software releases or manuscruipts
- I'd like to confirm the order of chapters as a way to help identify what sections go where. 
- `index.Rmd`: intro chapter, describe general value of openness (but forecast caveat about when this may not be appropriate); this should be reflected in the publishing chapter and cross-referenced elsewhere
- `project.Rmd`: 
  - minimize commentary on project components discussed at length in `teams.Rmd` (governance, contributing)
  - move "How should I manage data that can't be stored in version control?" to `publish.Rmd` (the latter is shorter than the other chapters right now)

**Comment by lwjohnst86** [comment]
@k8hertweck for now, I think putting the files into the py-rse folder would be fine. Of the three, `teams.Rmd` might be the most agnostic, since `project.Rmd` and `publish.Rmd` may have some differences between languages.

**Comment by gvwilson** [comment]
Can this now be closed?
