### ISSUE TITLE
Discussion: Lots of "How do I" but not enough exercises and "live coding" activities

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#282]
Looking the content over, I get the impression the material (mainly the RSE section) is more of a reference, but not really for a course. In a reference, I expect these types of headings to quickly look through to find what I want... sorta like an FAQ. But for a course, I expect much more "this is something, here is an exercise to test if you understand it". Very much related to #226 and #240, and was initially described at #44. I feel at this point we have too much content, and what we need is more exercises, live coding, and challenges, and much more practical (rather than theoretical concepts).

**Comment by joelostblom** [comment]
Today we discussed to edit RSE so that there is a coherent narrative and data sets throughout. In the discussion we also mentioned that it should be written more as a text book than a reference book so this issue could also be covered under that umbrella. Let's clarify at the next meeting

**Comment by lwjohnst86** [comment]
Half a dozen exercises per chapter. And more the better. Plus add live coding
