### ISSUE TITLE
Figure out CSS magic for separating prompt

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#289]
As per our meeting.

**Comment by joelostblom** [comment]
I looked into how to include the prompts a in R chunks previously. It is imperfect, and I found nothing about styling the prompt strings, they are just included as any other character in the code chunk. But maybe it can be helpful when you start looking into it more so I'm including a few links. I found that it is possible to change prompts based on language, but I could not find a way to change the continuation prompts https://stackoverflow.com/questions/39023509/changing-the-prompt-in-a-multilanguage-knitr-rmarkdown-document. For line numbers, I tried this https://stackoverflow.com/a/53280591/2166823 and this https://stackoverflow.com/a/25299194/2166823 but could not get it to work.

**Comment by gvwilson** [comment]
Is this still active?
