### ISSUE TITLE
Do we need the timezone info in the dog license data set?

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#297]
@gvwilson wrote on slack:

> However, the beginner Python volume still fails to build: Pandas complains that it can't subtract `datetime` objects if only one has timezone info (line 179). It looks like Madeleine was the last person to touch this - since she's out of action for a while, could someone else please have a look at this?

The reason for the failure is that the `animal_birth_month` column in the processed dog data set contains timezone data while the license related date columns do not. I believe this is a  unintentional consequence of the raw dog data set having date and time for the birth month column but just a date for the license columns (@lwjohnst86 please correct me if this was an intentional change made when processing the data). To be clear, this is the raw data format:

AnimalBirthMonth | LicenseIssuedDate | LicenseExpiredDate
-- | -- | --
05/01/2013 12:00:00 AM | 10/24/2014 | 11/15/2017
05/01/2014 12:00:00 AM | 10/25/2014 | 10/25/2019
07/01/2010 12:00:00 AM | 10/28/2014 | 09/24/2016

And this is the resulting processed data format:

animal_birth_month | license_issued_date | license_expired_date
-- | -- | --
2013-05-01T00:00:00Z | 2014-10-24 | 2017-11-15
2014-05-01T00:00:00Z | 2014-10-25 | 2019-10-25
2010-07-01T00:00:00Z | 2014-10-28 | 2016-09-24

Unless there is something in the data analysis lessons by @cwickham and @mbonsma that relies on the timezone data, I suggest that it is removed, is that fine with everyone? And maybe we can rename the column to `animal_birth_date` wile we are at it since it does not just contain the month?

**Comment by lwjohnst86** [comment]
Did PR that will address these problems.
