### ISSUE TITLE
Python data manipulation chapter code needs to be reorganized to be properly executed

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#298]
Partially related to #295, the Python data manipulation chapter does not have its code in linear fashion (top-to-bottom) for proper execution (e.g. `dog_licenses_large_boroughs`) and has some text that doesn't match the data ("convert to snake case" when the columns are already snake case).

**Comment by SaraMati** [comment]
I'm going over this
