### ISSUE TITLE
What source format(s) should we use for lessons?

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#3]
We need to write lessons in some format, but all options have shortcomings.

## Needs and Wants

1.  We *need* material to be **reviewable on GitHub**.

2.  We *need* to **generate HTML** (for online viewing) and **generate PDF** (for printing as a book).

3.  We *need* **cross-references** to sections, figures, tables, and bibliography entries.

4.  We *want* to be able to generate electronic books (.epub and .mobi).

5.  We *want* easy setup for local preview on Windows, MacOS, and Linux.

6.  We *want* a single source format rather than having different people use different formats for different languages.

7.  We *want* live documents (i.e., re-run code samples in the docs to regenerate output).

8.  We *don't want* to have to commit the output of compilation or translation to the repository.

9.  We *don't want* to have to build or maintain our own tools or templates.

## Notes

-   The open source version of GitBook is no longer being maintained.
-   Even if the format supports live documents, we may not use the capability in all cases.
    -   Tutorials often want to present snippets of code incrementally to build up to a larger solution,
        and neither R Markdown nor Jupyter Notebook supports that.
    -   Sometimes we only want some of the output from running a command (e.g., the first dozen lines).
        We can write and apply output filters for commands to handle this in most cases.
-   LaTeX requires more typing than Markdown, particularly when there are `lots` of `variable` names embedded `in the text`.
-   We don't have to use the same tools for writing lessons that we use when teaching, but it would be nice.
    -   Particularly since one of our lessons is "how do you publish computational research".

## Options

1.  GitHub Flavored Markdown + Jekyll (GitHub Pages)
    -   Pro:
        -   Easy to review.
        -   Generates HTML.
        -   Easy to set up for local preview.
    -   Con:
        -   Doesn't generate PDF.
        -   Doesn't do cross-references (would require our own tools/templates).
        -   Doesn't do .epub or .mobi.
        -   Doesn't support live documents.

2.  Pandoc + some flavor of Markdown.
    -   Pro:
        -   Easy to review.
        -   Generates HTML and PDF.
        -   Can do cross-references.
        -   Can do .epub and .mobi.
    -   Con:
        -   Have to maintain our own templates (and Pandoc isn't something many people speak).
        -   Have to commit results of compilation.
        -   Setting up for local preview can be complex.
        -   Doesn't provide live documents.

3.  LaTeX
    -   Pro:
        -   Easy to review.
        -   Generates HTML and PDF.
        -   Can do cross-references.
        -   Can do .epub and .mobi (ish).
    -   Con:
        -   Doesn't support live documents.
        -   Have to commit results of compilation.
        -   Have to write our own template (but that's not too hard).
        -   Generated HTML can require post-processing.

4.  R Markdown
    -   Pro:
        -   Easy to review.
        -   Generates HTML and PDF.
        -   Easy to set up for local preview.
        -   Live documents.
    -   Con:
        -   R-centric: supports other languages, but authors may not be familiar with it.
        -   Doesn't do cross-references.
        -   Have to commit the output of compilation.
        -   Generated output will require post-processing *or* we will have to maintain our own templates.

5.  Jupyter Notebook
    -   Pro:
        -   Generates HTML and PDF.
        -   Easy to set up for local preview.
        -   Live documents.
    -   Con:
        -   Difficult to review on GitHub.
        -   Python-centric: supports other languages, but authors may not be familiar with it.
        -   Doesn't do cross-references.
        -   Have to commit the output of compilation.
        -   Generated output will require post-processing *or* we will have to maintain our own templates.

**Comment by ljdursi** [comment]
Is 1 (GFM+Jekyll) necessarily incompatible with 2 (Some markdown flavour + Pandoc)?

I definitely lean towards the idea of using a markdown-type format for the body of the work, and generating other formats as needed; markdown + pandoc will give you good starter LaTeX, whereas LaTeX is harder to re-use unless you are more disciplined about separating format from content than I was during my LaTeX'ing days.

Having additional supplementary live worksheets in Jupiter sounds good but I'm a little more skeptical about using it for the bulk of the material?

**Comment by lwjohnst86** [comment]
The R package [bookdown](https://bookdown.org/yihui/bookdown/) basically has all your needs and wants. It's really well documented, uses Markdown, can use Python (change the knitr engine, which is super easy), can combine R and Python in same document (with reticulate), can generate html, epub, and pdf versions for books, plays really well with Git, CI, etc. Can do cross-referencing, labels, bibliography, etc. Most of the RStudio teams documents uses this for their documentation (e.g. https://r4ds.had.co.nz/).

**Comment by gvwilson** [comment]
I'm a bit nervous about bookdown because the free version of gitbook is now legacyware, but yes, it seems to have most of the features we want. Some questions:

1. If we put a list of key points or motivating questions or something in a document's YAML header, is there a way to get them out to display inside the page?

2. Same question, but is there a way to do this across all pages? For example, suppose each chapter defines a few learning objectives in its YAML header. We will want those displayed in the chapter, but also in an appendix that shows each chapter's learning objectives (i.e., the syllabus).

3. How do we mark up exercises and solutions? We appear to be able to create custom blocks - can they be nested so that a solution appears inside the corresponding exercise, or...?

**Comment by joelostblom** [comment]
I am a big fan of Pandoc for academic writing, so I am in favor for a markdown format that integrates well with Pandoc and supports most of its features. `.Rmd` via bookdown as suggested by @lwjohnst86  sounds like a great solution (although I haven't used that particular setup myself).

An alternative could be a documentation platform such as [`sphinx`](http://www.sphinx-doc.org/en/master/). I believe it addresses all the points listed in the OP. However, although markdown is supported, I have mostly seen it used with reStructedText, so there would probably be more of a learning curve, and I am generally more in favor for bookdown.

Related to point 7 from @gvwilson above, if we want to provide interactive live code *exercises* for learners, I recently heard about [the spaCy course creation framework](https://github.com/ines/spacy-course). It enables faded code samples where students can fill in the blanks, view hints, etc. To view an example, click on [2 - Getting Started via this link](https://course.spacy.io/chapter1). This would not be a replacement for any of the above, but possibly a compliment.

**Comment by lwjohnst86** [comment]
Bookdown infrastructure has been setup!
