### ISSUE TITLE
Do we want to make the first argument to `countwords.py` positional instead of controlled by the `--infile` flag?

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#308]
I am asking because the automate chapter does not use the flag currently, and before I add it to all the examples I just wanted to check if there is a specific reason we want to use a flag for input files. I am fine with either, but I think it is more common to pass input files as positional arguments: e.g. `python bin/countwords.py data/moby_dick.txt` instead of  `python bin/countwords.py --infile data/moby_dick.txt`.

If the flag is just there to differentiate when `stdin` should be used, I think it is nicer to rewrite the argparser to have `stdin` as the default if no positional argument is used. We just need to change this section

```python
    parser.add_argument('--infile', type=str, default=None,
```

to

```python
    parser.add_argument('infile', type=str, default=sys.stdin, nargs='?',
```

and higher up just change `if args.infile:` to `if args.infile != sys.stdin:`.

I can make this changes unless everyone else has used `--infile` a lot already and would have to rewrite. If we don't plan to use `stdin` with `countwords.py` in any chapter, we can simplify further, but I am not sure if it is there to be taught specifically with pipes somewhere. @DamienIrving You have the best overview, let me if this makes sense or if I am missing something.

**Comment by joelostblom** [comment]
I should add that in `collate.py`, the input files are passed as positional arguments:

```python
    parser.add_argument('infiles', type=str, nargs='*', help='Input file names')
```

**Comment by lwjohnst86** [comment]
I agree to this. +1

**Comment by DamienIrving** [comment]
@joelostblom Great idea regarding `countwords.py`. Like you suggested, the only reason I used `--infile` was that I wanted to be able to use standard input and I hadn't thought of setting `default=sys.stdin`. Do you want to go ahead and make that change to `countwords.py` in #309 ?

With respect to `plotcounts.py`, if we make `infile` a positional argument that means it will have two positional arguments (`infile` and `outfile`). That means the following pipeline would break, right?

```
$ python countwords.py ../data/anne_of_green_gables.txt | python plotcounts.py anne.png 
```
