### ISSUE TITLE
Discussion: Add the output from `tree` in the beginning of each/some RSE chapters?

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#310]
To orient students about what the current file structure should looks like. I think this is important for the chapters that builds on files being created in the previous chapters.

**Comment by lwjohnst86** [comment]
Before we have this, we would need to have a solid "path" between chapters of what is being created etc. Maybe make individual folders based on what the package should look like?

**Comment by DamienIrving** [comment]
As well as the current state of the project directory structure, some chapters may also need to provide the current state of scripts that are under development (e.g. the `plotcounts.py` script).
