### ISSUE TITLE
Address build warnings if needed

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#320]
Just an issue to remind us to explore if we need to address the warnings when building before publishing, mostly latex ref issues.

[Example log](https://travis-ci.org/merely-useful/merely-useful.github.io/jobs/640930266?utm_medium=notification&utm_source=github_status), search for "warning".

**Comment by joelostblom** [comment]
@gvwilson This is not the same issue @lwjohnst86  was talking about, but I am assigning this to you also in case you are still bored after fixing Luke's issue. These are just warnings, not errors, mostly latex related. Maybe we not need to fix right away but just to get an idea if this is easy to fix or remove the references (or just ignore).

**Comment by joelostblom** [comment]
Importantly I don't see this in the more recent https://travis-ci.org/merely-useful/merely-useful.github.io/builds/653172622?utm_source=github_status&utm_medium=notification, but I am not sure if that is because it failed on something else earlier in the build process.

**Comment by lwjohnst86** [comment]
I couldn't resolve the LaTeX problems, which I tried in #335. I removed PDF generation for now.
