### ISSUE TITLE
Proposal: Move Python Packaging to above Unit Testing and CI

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#322]
## Proposal

Move the Python Packaging Chapter to before Unit Testing Chapter. See PR #321 for the update.

## Background

Unit testing and the associated continuous integration really only make the most sense (from a RSE-perspective, emphasis on the software part) in light of actually testing a *software* package. For the unit testing, trying to design exercises and content around the scripts the previous chapters build up and use from is quite difficult (see some of the discussions at #317). Likewise, the next chapter is continuous integration which works best with packages (even though it can be used with anything). Since CI was developed specifically for running tests for packages and checking that packages get built, this is a natural fit. Likewise, with this new ordering, the Python Packaging flows nicely from the previous Project Structure Chapter.

## Pros and Cons

**Pro:**
-   It just flows better and makes it easier to structure the CI and Unit Testing chapters.

**Con:**
-   It may require some re-working for anyone working on the later chapters.

**Comment by k8hertweck** [comment]
Agreed at our Feb 6 meeting that this change will work for py-rse. Initial intent was that R packaging has unit-testing baked-in, so we can revisit original structure with r-rse.
