### ISSUE TITLE
Should people work in forked repos or in this repo?

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#33]
Do we prefer to work in our own forks of this repo, or to create branches in this repo?

**Comment by lwjohnst86** [comment]
Can we do both? What are the advantages/disadvantages to either?

**Comment by DamienIrving** [comment]
Forks might be less messy?

**Comment by mbonsma** [comment]
My vote is for forks and PRs into the main repo from forks. Or PRs into a development branch in the main repo.
