### ISSUE TITLE
Target location for generated online book? Here or in individual repos?

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#34]
We've got a problem when building into a `gh-pages` branch when the main repo is called `*.github.io`. When a repo is appended with `.github.io`, the source material [seems](https://help.github.com/en/articles/user-organization-and-project-pages) to be required to be in the parent folder... which won't work with with the `gh-pages` route or the `docs/` folder route. If we rename the repo (as I suggested in #28) then we can use the `gh-pages` route but then the URL looks something like `merely-useful.github.io/merely-useful`... which isn't ideal.

A couple workarounds that I can think of... 

1. Rename the repo to something like `main` or `source`. Then with some scripts we can have each individual individual book pushed to their respective repos `still-magic` and `one-extra-fact`. Each book would then have the output look something like `merely-useful.github.io/still-magic` and `merely-useful.github.io/one-extra-fact`.
2. Or we use [master for website deployment](https://github.com/11ty/eleventy-base-blog/issues/11) and "source" (or other) branch for the original source material. Then deploy to master and protect master so no one can push to it except for being built by Travis.

I think in the end having two URL paths for each of the two books would be desirable, but that may take some additional considerations before doing that. We could for now do 2 and later on do something like 1.

**Comment by gvwilson** [comment]
I like option 2 - use `published` (or a similar name) for the main branch and use Travis to build that and push it to `master` (which nobody ever commits to directly). This lets us keep everything in one repository, which I believe will make management a lot easier during development.

**Comment by gvwilson** [comment]
#35 tackles this by using parts to divide the material for the three books (novice R, novice Python, intermediate/RSE material).
