### ISSUE TITLE
Discussion: Persona last names, or other ideas for people in Git chapters

### ISSUE THREAD

**Issue by cwickham** [merely-useful/merely-useful.github.io#340]
The git lessons used the member of the ENIAC project as users:
* [Frances Bilas in `git-cmdline.Rmd`](https://github.com/merely-useful/merely-useful.github.io/blob/aaef6cf97996e00f6d03282ed2320edc1a6a4f98/py-rse/git-cmdline.Rmd#L22-L25)
* [Frances Bilas and Jean Jennings in `git-advanced.Rmd`](https://github.com/merely-useful/merely-useful.github.io/blob/aaef6cf97996e00f6d03282ed2320edc1a6a4f98/py-rse/git-advanced.Rmd#L653-L657)

I've used one of our [learner personas](https://merely-useful.github.io/py-rse/index.html#rse-intro-personas), Amira, in my rework of `git-cmdline.Rmd`, but [I need a lastname](https://github.com/merely-useful/merely-useful.github.io/pull/306#discussion_r386080200).  **How do people feel about "Amira Khan"?**

@SaraMati will need a second user for `git-advanced.Rmd`.  Should it be another one of our personas, Sami?  **What should their last name be?**

**Comment by joelostblom** [comment]
Khan sounds good. Following the same royal reasoning we could have "Sami Wang", although I personally like the sound of "Sami Weaver" which was just a name that popped up when I looked around. Or something Finnish...

**Comment by DamienIrving** [comment]
I guess we want to pick surnames that typically go with those first names? If so, here's what google tells me about those first names:

## Amira
"Amira is an Arabic female given name, meaning "princess", and a Hebrew female given name, meaning 'treetop' or 'saying'."

Khan is a very common surname in the Arab world, so Amira Khan sounds good.

## Sami
"Sami can be an Arabic name meaning elevated or sublime, or a Turkish name, a Finnish male name derived from Samuel, or an American name abbreviated from Samantha or Samuel."

The pronouns used for Sami in the personas are they/them, so we can interpret it as a male or female given name. If we went with Joel's suggestion of a Finnish surname we could go with Sami Nieminen or Sami Heikkinen or something like that?

**Comment by cwickham** [comment]
To keep a complete record, from @gvwilson in Slack:
> how about "Sorva" as a last name? "Sami Sorma" would be Finnish...

**Comment by DamienIrving** [comment]
We also need a last name for Jun...

**Comment by gvwilson** [comment]
Jun Hsu ?

**Comment by DamienIrving** [comment]
Suggestion from @gvwilson: Sami Virtanen (Finnish)

**Comment by DamienIrving** [comment]
Got a few thumbs up on slack for Virtanen, so unless there's any strong objection I'm going to say that we settle on:
- Amira Khan (she/her)
- Sami Virtanen (them/they)
- Jun Hsu (he/him)
