### ISSUE TITLE
Rename mymodule.py. to csv_tools.py or similar

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#352]
More realistic naming https://github.com/merely-useful/merely-useful.github.io/pull/341#discussion_r392629813

**Comment by DamienIrving** [comment]
Turns out most sensible names for the module (e.g. `csvtools`, `csvuitls`, `csvio`) already exist as python packages, so I might hold off on renaming `mymodule` at this stage.

Unless anyone can come up with a good unique name?

**Comment by DamienIrving** [comment]
We've gone with `utilities`.
