### ISSUE TITLE
Proposal: point at Carpentry installation instructions

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#365]
## Proposal

What precisely is being proposed (longer than issue subject line, but no more than 2-3 sentences).

## Background

Forces at play, previous discussion, etc.

## Pros and Cons

**Pro:**
-   One
-   Two
-   Three

**Con:**
-   Four
-   Five
-   Six

## Alternatives

Other options and why they are less good than the proposal.

**Comment by DamienIrving** [comment]
This issue is now covered in #435.
