### ISSUE TITLE
Discussion: title/purpose

### ISSUE THREAD

**Issue by danielskatz** [merely-useful/merely-useful.github.io#368]
I wonder if this lesson project might have a more understandable title.  I feel like "merely useful" is part of an insiders joke, and "RSE Python" is also a bit unclear.  Maybe something like "Python for RSEs" would be easier for outsiders to find and understand.  Or "Python for Future RSEs"?

I wish I could offer a better suggestion, but I just can't completely figure one out, in part because the introduction (particularly the second paragraph) isn't clear either.

**Comment by lwjohnst86** [comment]
Thanks @danielskatz we'll consider it!

**Comment by gvwilson** [comment]
The title will probably wind up being something like "Research Software Engineering with Python" (or "with R" for the companion volume) - the publisher will have final say.
