### ISSUE TITLE
Discussion: royalty arrangements

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#375]
Given the number of contributors, we're only like to see a couple of hundred dollars each in royalties (if that), and reporting that for taxes will be a pain for those of us outside the US. We could instead have the publisher donate royalties directly to a charity of our choice. (We can also ask for a slightly higher royalty rate, since they're going to get the tax offset for the charitable donation.)

We therefore have two questions to discuss:

1.  Do we donate to charity or divide amongst ourselves?
2.  If we donate to charity, which one?

-   @gvwilson
    1.  Charity.
    2.  The Carpentries

**Comment by k8hertweck** [comment]
I am very happy to donate to charity. Given the amount of material we adapted from The Carpentries, I think it would be reasonable for the funds to go to them.

**Comment by lwjohnst86** [comment]
Happy to donate to a charity. Carpentries is fine with me too.

**Comment by SaraMati** [comment]
Charity-Carpenteries here as well

**Comment by DamienIrving** [comment]
I'm also supportive of donating the money to The Carpentries.

**Comment by mbonsma** [comment]
Agree - charity, and The Carpentries is a great choice.

**Comment by ChristinaLK** [comment]
Charity 100% and The Carpentries sounds good to me.

**Comment by joelostblom** [comment]
The Carpentries sounds good!

**Comment by cwickham** [comment]
I'm happy with donating royalties to Carpentries too.

**Comment by elliewix** [comment]
+1 for carpentries donation.

**Comment by lwjohnst86** [comment]
I assume this is revised? Closing
