### ISSUE TITLE
Discussion: authors vs. acknowledgments

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#376]
As we go into the last [sic] lap, we need to figure out whose names will be on the cover and who will be listed in the acknowledgments for this volume. One way to figure this out is to use two passes:

1.  Everyone who thinks they _should_ be on the author list puts their name forward.
2.  Once that list stabilizes, the people on it may propose and vote on others that they think should be included, but were too modest to put themselves forward.

Thoughts?

**Comment by k8hertweck** [comment]
This sounds like a reasonable process. In the interest of managing expectations, I want to also clarify:
- we would do this process now for the Python RSE book
- the process for Python RSE is independent of the other books (R RSE and intro R/intro Python), we'll perform the same process for each of the others if/when they develop to publication stage

**Comment by lwjohnst86** [comment]
Agree with @k8hertweck. And I guess I'll start, I think I should be an author :stuck_out_tongue:

**Comment by DamienIrving** [comment]
I also agree with @k8hertweck. I think I should be an author of the Python RSE book :smile:

**Comment by mbonsma** [comment]
Sounds like a good process! I **don't** think I should be an author of the Python RSE book, having been completely out of the loop for the past 6 months :)

**Comment by ChristinaLK** [comment]
I am in the same boat as @mbonsma. :) **No** authorship for me.

**Comment by joelostblom** [comment]
Agree with what have been said so far, I think I should be an author on Python RSE.

**Comment by elliewix** [comment]
I'm fine not being an author. Not what I had intended when we started out, but external factors forced me to be absent.

**Comment by gvwilson** [comment]
Resolved.
