### ISSUE TITLE
Format contributors' names on title page

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#39]
Modify template to format authors' names on title page of HTML and PDF more sensibly.

**Comment by lwjohnst86** [comment]
Seems the only way to modify this behaviour is by modifying the pandoc html/latex templates.

A good work around is to list all authors on a single line, as done [here](https://github.com/rstudio/rmarkdown-book/blob/master/index.Rmd).

**Comment by lwjohnst86** [comment]
Looks like this: 
![Screenshot from 2019-05-08 19-04-20](https://user-images.githubusercontent.com/6662983/57393792-26ccde80-71c4-11e9-928e-0474561f3f62.png)
