### ISSUE TITLE
What material can we recycle?

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#4]
Please add comments to this issue pointing at existing material we might be able to re-use.

-   Relevant to our topics.
-   Compatible license (we will be CC-BY).
-   Accessible source (we will *not* OCR any JPEGs).

**Comment by gvwilson** [comment]
-   Unix shell
    -   [Software Carpentry lesson on the Unix shell](http://swcarpentry.github.io/shell-novice/)
    -   [Data Carpentry Genomics lesson on the Unix shell](https://datacarpentry.org/shell-genomics/)
-   Git
    -   [Software Carpentry lesson on Git](http://swcarpentry.github.io/git-novice/)
-   Python
    -   [Software Carpentry lesson on Python](http://swcarpentry.github.io/python-novice-gapminder/) (new one using data analysis)
    -   [Data Carpentry lesson on Python](https://datacarpentry.org/python-ecology-lesson/)
-   R
    -   [Software Carpentry lesson on R](http://swcarpentry.github.io/r-novice-gapminder/) (tidyverse version)
    -   [Data Carpentry lesson on R for ecologists](https://datacarpentry.org/R-ecology-lesson/)
    -   [Data Carpentry lesson on R for social scientists](https://datacarpentry.org/r-socialsci/)
-   SQL
    -   [Software Carpentry lesson on SQL](http://swcarpentry.github.io/sql-novice-survey/)
    -   [Data Carpentry lesson on SQL](https://datacarpentry.org/sql-ecology-lesson/)
-   Testing
    -   [Katy Huff's lesson on testing](http://katyhuff.github.io/python-testing/)
-   Data wrangling
    -   [Data Carpentry lesson on spreadsheets for ecologists](https://datacarpentry.org/spreadsheet-ecology-lesson/)
    -   [Data Carpentry lesson on spreadsheets for social scientists](https://datacarpentry.org/spreadsheets-socialsci/)
    -   [Data Carpentry lesson on OpenRefine for ecologists](https://datacarpentry.org/OpenRefine-ecology-lesson/) 
    -   [Data Carpentry lesson on OpenRefine for social scientists](https://datacarpentry.org/openrefine-socialsci/)

**Comment by joelostblom** [comment]
- Python
    - The [four notebooks linked under the schedule section here](https://uoftcoders.github.io/2018-09-10-utoronto/) from a UofTcoders 2-day workshop. Modelled of the data carpentry workshop but with additional emphasis on data wrangling, faceted visualization in seaborn, and with a more accessible data set (gapminder).
        - Needs a little bit of cleanup from my side.
- R
    - The [course in Quantitative Methods in R for Biology](https://uoftcoders.github.io/rcourse/) that we created in UofTcoders together with the ecology department at UofT. The course is designed to teach skills needed for reproducible, openly accessible, analytically thorough, and well documented science (it also includes how to develop ecological population models).

**Comment by mbonsma** [comment]
We could probably also use things from the [UofT Coders lesson bank](https://uoftcoders.github.io/studyGroup/lessons/) - there might be some topics in here that are more niche that can be slotted in as needed.

For example, here are a few that align with the topics in the Merely Useful outline:

* Git
  * [Continuous integration](https://uoftcoders.github.io/studyGroup/lessons/git/ci-github/lesson/)
  * [Using branches in Git](https://uoftcoders.github.io/studyGroup/lessons/git/branches/lesson/)
  * [Web design with Jekyll and GitHub Pages](https://uoftcoders.github.io/studyGroup/lessons/misc/jekyll-ghpages/lesson/)

* Python
  * [Creating packages](https://uoftcoders.github.io/studyGroup/lessons/python/packages/lesson/)
  * [Unit testing](https://uoftcoders.github.io/studyGroup/lessons/python/unittests/lesson/)

* R
  * [RStudio debugging](https://uoftcoders.github.io/studyGroup/lessons/r/debugging/lesson/)

**Comment by lwjohnst86** [comment]
Good resources so far. I've created (or been involved in creating) several material as well:

- R:
    - [Data analysis workflow in R](https://dda-rcourse.lwjohnst.com/) for biomedical/diabetes researchers (includes material on open science as well) ([GitHub repo](https://gitlab.com/lwjohnst/dda-rcourse))
    - [FAIR-R](https://github.com/TIBHannover/FAIR-R) workshop modified from the SWC material (focused around the FAIR principles)

I have a bank of material for workshops I ran here at Aarhus in Denmark (many based around the UofTCoders material): [website](https://au-oc.github.io/content/) and [GitHub repo](https://github.com/au-oc/content)

**Comment by ChristinaLK** [comment]
Karl Broman has some good tutorials, this is possibly the one most relevant for this course (on building R packages): https://kbroman.org/pkg_primer/

There's already some git links above, but Jenny Bryan's Happy w/ Git and Github for the UseR: https://happygitwithr.com/

**Comment by DamienIrving** [comment]
Some MIT faculty have put together a course called "The Missing Semester of Your CS Education." It has some overlap with our RSE lessons. https://missing.csail.mit.edu/

**Comment by DamienIrving** [comment]
[The Turing Way](https://the-turing-way.com) is an online open source book on reproducible data science.
