### ISSUE TITLE
Fig 2.2 is missing the amira directory under Users

### ISSUE THREAD

**Issue by cwickham** [merely-useful/merely-useful.github.io#427]
Figure stored at `figures/shared-rse/bash-basics/sample-filesystem.png`

Referenced at:
https://github.com/merely-useful/merely-useful.github.io/blob/1e4741411d123fd861035e2e44df15b14504dd66/py-rse/bash-basics.Rmd#L157-L165

**Comment by k8hertweck** [comment]
I'm on it; thanks for the catch
