### ISSUE TITLE
Discussion: Project Structure Reorganization

### ISSUE THREAD

**Issue by cwickham** [merely-useful/merely-useful.github.io#429]
I think here are three big pieces in the current chapter:

* Introducing the project structure from Noble, and discussing its components
* Documenting code/software
* Documenting data

Roughly, I suggest we:

* Extract the first piece into its own structure chapter, and move it much earlier in the book.
* Move the code/software documentation into `packaging`.
* Move the data documentation into `provenance`.

## Possible locations for `project`

* Between `git-advanced` and `teams`.  We have a lot of the folder structure and a README, but we'll need to link forward to things like `LICENSE` and `CONDUCT`

* After `teams`.  We have the folder structure and many standard files, but in practice, you might think about structure before on-boarding more people.

* Inside `teams`.  We make this a section of `teams`.  It is nicely linked but I think a standalone chapter is useful to point to from other places.

## Section by section changes to `project`

* **Intro** Keep, and add that we've been following a particular structure, but it's a good time to talk about what that structure is and why we've been following it.

* **What is a Project? {#project-scope}** Keep 

* **Standard Information {#project-boilerplate}** Keep  
    Currently well linked back to relevant chapters (`git-advanced` and `teams`)

* **Organizing Project Content {#project-organize}** Keep

* **Using Compiled Programs {#project-mixed}** ?  
    We currently don't have any do we?  Do we need this section? I think it's useful to know about for navigating other projects, but there is a lot here that is hard to get a grip on with no example from the narrative.  

* **Documenting Software {#project-software-docs}** Rework

    I suggest a title change **Documentation**, then use it as an introduction to `docs/` and `reports/`.  Move all other software specific sections to `packaging`: 
    * The kinds of documentation
    * **What to Document {#project-docs}**
        Also link forward to this from where docstrings are introduced
    * **Creating a FAQ {#project-faq}**

* New section **Data**  
    Since the other sections are working through Noble's structure, we should talk about `data/` here too. At this point, maybe just talk about our decision to store raw data in Git, and the importance of a `README.md` in `data/`.  
    
* **Data versus Code {#project-data-vs-code}** Integrate with `provenance`

* **Managing External Data {#project-external}** Keep and merge with **Data** section above.

**Comment by lwjohnst86** [comment]
Completely on board with these suggestions. I can help with the re-work if we go ahead with this.

**Comment by cwickham** [comment]
Meeting 07-23-2020: Move project structure to intro when project is first introduced. I'll work on a PR to do this, and move other pieces to `packaging` or `provenance` as appropriate.

**Comment by DamienIrving** [comment]
Now that #431 and #433 are merged I think this issue has been resolved?
