### ISSUE TITLE
Proposal: Add a completed project listing as an Appendix

### ISSUE THREAD

**Issue by cwickham** [merely-useful/merely-useful.github.io#432]
## Proposal

Include the complete tree for `zipf` as an Appendix, with each file linked to the chapter/section it is introduced.  

## Background

@DamienIrving provided a great complete tree for `zipf` in #430.  The complete tree is pretty complicated, so I didn't include the full thing in the re-working of project structure #431.  However, it would be nice to be able to link to the complete tree, and it also provides a useful way for a reader to navigate the book.

## Pros and Cons

**Pro:**
-   Adds an additional way to navigate text
-   Not too much work to implement beyond what Damien has already provided

**Con:**
-   One more thing that needs to stay updated if the content of the project changes

## Alternatives

Do nothing in the book, and use the GitHub account for our characters to perform this service.

**Comment by k8hertweck** [comment]
I really like this idea; the truncated `tree` output at the beginning of each chapter provides minimum info, but a specific place to look for the complete project would be great (and something I wish we'd had all along!)

**Comment by DamienIrving** [comment]
I like this idea too. For now, #434 contains a new file `py-rse-final-tree.md` which shows the whole tree (I missed a few files in https://github.com/merely-useful/merely-useful.github.io/issues/430#issuecomment-663283957). We could convert that file to an appendix before or after that PR is merged.
