### ISSUE TITLE
Revise chapter on automation with Make

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#48]
`automate.Rmd` is ready for serious revision:

-   Diagrams, diagrams, diagrams
-   More exercises
-   Decide whether to keep as one chapter or split into two
-   Decide whether to include one section each on a Python-based tool and an R-based tool for task automation
-   Work in at least one other running example

**Comment by lwjohnst86** [comment]
Closing as this was added in automate.
