### ISSUE TITLE
Proposal: workflow for overhauling existing chapters

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#50]
## Proposal

When doing a major overhaul of an existing chapter:

1.  Create an issue titled `Revise chapter on ...subject...`
2.  Label the issue with the volume (novice R, novice Python, or intermediate).
3.  Assign it.
4.  Create a small change to the chapter's `.Rmd` file, commit that, and create a PR.
    1.  Mention the issue in the first line of the PR comment body.
    2.  Assign the PR.
    3.  Mark it as `work in progress`.

## Background

1.  We want to be sure people don't accidentally collide.
2.  Some changes to chapters will be small and independent, but major overhauls may want review over multiple revisions. This proposal creates a long-lived PR where writers and reviewers can discuss changes.

## Pros and Cons

**Pro:**
-   Simple.

**Con:**
-   Long-lived PRs with lots of changes are generally not a great idea for software, but this isn't software.
-   This may not be an appropriate workflow for refactoring (e.g., splitting chapters into smaller pieces or merging them).

## Alternatives

-   Lots of little PRs for individual changers to chapters
    -   But each chapter should have a strong narrative thread, so the work should be done as a unit.

**Comment by lwjohnst86** [comment]
I approve this proposal (I won't be able to attend the next meeting)
