### ISSUE TITLE
Proposal: do all work in this repository

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#6]
## Proposal

Rather than dividing content between two repositories, we should put all material in this repository during development.

## Background

I initially created *three* repositories for beginner, intermediate, and advanced material, but quickly realized that there were really only two courses. Since then, I have frequently moved material back and forth between the repositories for those two courses, losing history or making it difficult to find. Since we are likely to continue to shuffle material, I propose that all work be done in a single repository, and that we use this one for that purpose.

## Pros and Cons

Pro:
-   one place to look for everything
-   much easier to shuffle material around

Con:
-   we may want to separate material at the end

## Alternatives

-   leave material in separate repos

**Comment by lwjohnst86** [comment]
I like the simplicity and retention of history with the "single repo" approach. Plus, we could theoretically write a script to autogenerate each course into their own repos as bookdown websites.

**Comment by gvwilson** [comment]
Approved in #7.
