### ISSUE TITLE
Add in CONTRIBUTING the details for using Python packages in the book

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#65]
Since Travis is a clean environment, the packages you use or depend on must also be installed. There are some fairly simple steps to take to get Travis to install them, which will be described in the README.

**Comment by lwjohnst86** [comment]
For any Python users, what's the conventional way of indicating dependencies and then installing them via Travis? I am aware of the `requirements.txt` file and then running `before_script: python requirements.txt` or something... is that the correct/"best" way?

**Comment by joelostblom** [comment]
I believe you can put `pip install -r requirements.txt` under the `install:` section. It seems like you [might need to add `--user` if python is not set as the language](https://docs.travis-ci.com/user/languages/python/#dependency-management). Admittedly, I don't use Travis much so let's see if someone else can confirm.

**Comment by ljdursi** [comment]
Yup, @joelostblom, that's the canonical way, with the caveat that we'll have to make sure we have the 'right' python installed before then; and if it's the one of the system pythons, the preferred way to install some large packages with complex dependencies is not via pip but through system packages, e.g. we'd add

```
addons:
  apt:
    packages:
    - python3-numpy
    - python3-scipy
    - python3-matplotlib
```
