### ISSUE TITLE
Proposal: adopt outline for novice material in #63

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#68]
## Proposal

We should adopt the outline in #63 as a starting point for work on the novice R and novice Python books on the understanding that content will expand or be moved around as work proceeds.

## Background

#63 describes a course that covers:

- data manipulation
- plotting
- programming (writing functions, using the IDE, installing packages)
- data analysis
- verification (which may be moved into the intermediate material)
- version control
- publishing
- reproducibility (which may wind up being combined with "programming")
- collaboration

We almost certainly *can't* cover more than this in a one-semester course, and most instructors will probably cover less (particularly if they want to include more statistics or domain-specific examples).

## Pros and Cons

**Pro:**
-   These are all core skills.
-   The same outline ought to work for both R and Python.
-   It provides a solid base for the intermediate course.

**Con:**
-   This may still be too much material.

## Alternatives

N/A - this is a starting point for our work, and will evolve as we write.

**Comment by elliewix** [comment]
Reproducibility at the first semester level can sometimes be threaded through conversations about coding style and file naming conventions.  eg use a script for R and don't do all your work just within the console.

**Comment by DamienIrving** [comment]
Passed at meeting on 29 May 2019.
