### ISSUE TITLE
Discussion: should we cover regular expressions?

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#71]
1.  Should we cover regular expressions?
2.  If so, should they go in the novice or intermediate material?

**Comment by lwjohnst86** [comment]
Definitely not novice. Intermediate if there is space... looking more like we need an "advanced" version as well :wink:

**Comment by gvwilson** [comment]
I think the intermediate material fans out from the novice material, so we can have sections in the intermediate that instructors and learners pick and choose from.

**Comment by joelostblom** [comment]
Maybe - intermediate / advanced. Build from using wildcards with ls and find. Maybe only show a few common and especially useful cases.

**Comment by ljdursi** [comment]
I'd be completely in favour of leaving regular expressions out entirely unless we an example we were pursuing required them.  They're a useful tool to have in your back pocket, but that's true of a _lot_ of things...

**Comment by lwjohnst86** [comment]
As per #70, leave out and focus on current content. Closing and adding "on hold" label.

**Comment by gvwilson** [comment]
Proposal: add a short chapter on regular expressions in Python between `bash-advanced` and `py-scripting`.

**Comment by joelostblom** [comment]
An alternative suggestion is to not use `\w+` and instead  split on whitespace while highlithing that this approach is incomplete but sufficient for this example.

**Comment by DamienIrving** [comment]
I'm not sure that we should devote an entire chapter to a topic that really isn't a must-know for writing and packaging python software.

Given that we only have two lines of code involving regular expressions,
```
findwords = re.compile(r"\w+", re.IGNORECASE)
word_list = re.findall(findwords, text)
```
perhaps it would be sufficient to include an info box just after those lines of code are introduced? Something along the lines of...

> **Regular expressions**
>
> Quick explanation of the concept and a link to further information/resources.
