### ISSUE TITLE
Proposal: cover defensive programming in novice lessons, leave unit testing to intermediate

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#75]
## Proposal

The novice material should show people how to add assertions to their scripts and functions to check that things are behaving as expected, but discussion of writing and running explicit unit tests should be moved to the intermediate material.

## Background

Unit testing is an essential part of developing robust, reusable software, and should be part of every software engineer's training. However, many data scientists (including @cwickham and @joelostblom from this team and several people from RStudio) feel that it isn't the right paradigm for novice data scientists. They are usually creating scripts to get specific answers from specific datasets, rather than writing tools for future use by themselves or others, and they can't write useful unit tests in many cases because they don't know what the expected output is for realistic input. (If they did, they would have published their results and moved on...)

After discussion with several data scientists, it seems that the usual way to check the correctness of an analysis is to inspect intermediate results and look for outliers, unusual gaps, and so on. Rather than unit tests of reusable functions, it seems that teaching people to embed assertions to make these checks explicit and repeatable is a more realistic goal for the novice course than classic unit testing, which would then be covered in the intermediate material (because people taking that course *are* building software meant for use by others in multiple situations).

## Pros and Cons

**Pro:**
-   Learning how to write useful assertions is a necessary part of writing unit tests.
-   Defensive programming is a more faithful representation of what most working data scientists do than unit testing, and hence more likely to be taken seriously by learners.
-   Unit testing is less important to novices than other topics we want to cover.

**Con:**
-   The less we teach about testing, the less important the audience will believe it is.
-   The less we teach about testing, the less seriously some potential instructors might take our material.

## Alternatives

The alternative is to include unit testing in the novice course.

**Comment by joelostblom** [comment]
For exploratory data analysis, I am also in favor for understanding how to carry out less automatic sanity checks such as plotting to check that a data transformation makes sense or seeing if there are extreme values impacting your data summaries (or feature scaling). Similar to what @cwickham mentioned earlier:

> Testing in this context might be less formal than unit tests and involve data summaries, tables or plots that the reader/analyst can use to verify things went as planned.

**Comment by mbonsma** [comment]
In my own experience, unit testing is an advanced skill (i.e. I rarely do it), so I support this proposal.

**Comment by lwjohnst86** [comment]
Pass in 2019-06-11 meeting
