### ISSUE TITLE
Discussion: Have meeting agenda and minutes as files or in Wiki?

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#76]
I tend to remove Wiki's from GitHub repo's since (for me) they tend to distract and they are just an extra place I have to remember to look (and I always forget to look there). The latest agenda is on the Wiki and since meeting agenda and meetings aren't part of the course material, it may make sense to use the Wiki instead of as files. @gvwilson since you started with files and @DamienIrving since you used the Wiki, what are both your thoughts on this? I'm impartial, but I think we should be consistent (which, at least for me, really helps staying organized). 

Thoughts?

**Comment by gvwilson** [comment]
I prefer to keep things in the repo rather than the wiki because the repo allows pull requests (and comments thereon), but wiki pages don't. I'm not strongly attached, though, and I take @lwjohnst86's point about meeting agendas not being part of the book per se.

**Comment by DamienIrving** [comment]
I'm in favor of a wiki because (a) agenda's aren't part of the book, and (b) pull requests etc seem like overkill for agenda management.

**Comment by gvwilson** [comment]
I volunteer to move old agendas into the wiki.

**Comment by lwjohnst86** [comment]
Decided as in May 28th meeting
