### ISSUE TITLE
Dig into AirBnB data disclaimers and legal / ethical issues

### ISSUE THREAD

**Issue by mbonsma** [merely-useful/merely-useful.github.io#82]
As a group we had concerns about using the [AirBnB data](https://github.com/merely-useful/merely-useful.github.io/issues/14#issuecomment-489113807) out of the box as an example dataset, so I will do some research to set up this dataset as an example of how to evaluate ethical and legal concerns around open data.

Possible resources:
* [Disclaimers](http://insideairbnb.com/about.html#disclaimers) on the AirBnB data website
* Research about data ethics 
* Other examples of open data gone wrong? (thinking of the OKCupid one, but there may be others).

**Comment by cwickham** [comment]
Might be good to link to some of the ethics codes for data practitioners:

 * [American Statistical Association Ethical Guidelines for Statistical practice](https://www.amstat.org/ASA/Your-Career/Ethical-Guidelines-for-Statistical-Practice.aspx)
 * [The Global Data Ethics Project](https://www.datafordemocracy.org/project/global-data-ethics-project)
* [Data Practices - Values and Principles](https://datapractices.org/manifesto/)

**Comment by mbonsma** [comment]
Thanks @cwickham, these are super helpful!

**Comment by lwjohnst86** [comment]
As per our last meeting, PR for datasets we will use is #126. Closing this for now.
