### ISSUE TITLE
Discussion: How do we name files for Novice R and Python?

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/merely-useful.github.io#84]
So far Novice R and Novice Python files are prefixed with `novice-r-` and `novice-py-`. Since each file is a considered a chapter, and since (at least for the novice material) materials are split by language, we need some system to separate the Python and R chapters.

Do we simply prefix each file with `novice-r-` or `novice-py-`?

**Comment by joelostblom** [comment]
Maybe just `r-`, `py-`, and `int-` for brevity?

**Comment by DamienIrving** [comment]
Note: `rse` instead of `int`

**Comment by lwjohnst86** [comment]
Brief versions passed during meeting in 2019-06-11
