### ISSUE TITLE
Intermediate subsection assignment: R logging

### ISSUE THREAD

**Issue by ljdursi** [merely-useful/merely-useful.github.io#88]
This issue tracks the [logging section for R](https://github.com/merely-useful/merely-useful.github.io/blob/book/intermediate-goals.Rmd#L84-L88) in the intermediate material.

This issue can be closed when 
- [ ] There are an initial set of R exercises corresponding to the outline of the logging material in the Reproducible Software section (which may evolve as part of this task)
- [ ] There is a first draft of the text of the subsection for R in the intermediate material.

**Comment by ljdursi** [comment]
Was this intended to be the entire reproducible software section, or just the logging component?

**Comment by gvwilson** [comment]
Just logging for now please.

**Comment by DamienIrving** [comment]
Did we decide in the last meeting that logging is not going to be included?

**Comment by gvwilson** [comment]
Yes - I'm sorry to see it go, but the world is a cold, harsh place.
