### ISSUE TITLE
Novice R section assignment: Getting Started

### ISSUE THREAD

**Issue by cwickham** [merely-useful/merely-useful.github.io#95]
This issue tracks the [Getting Started](https://github.com/merely-useful/merely-useful.github.io/blob/925ff17ea8b0b5aa5fa15d219a8b9012e533397c/novice-goals.Rmd#L7-L20) section for the novice R material.

This issue can be closed when:

* [ ] There are an initial set of R exercises corresponding to the outline
* [ ] There is a first draft of the text of the section

**Comment by ChristinaLK** [comment]
My "python" version of this is here (merged), may be helpful. 

#121
