### ISSUE TITLE
Novice R section assignment: Data Manipulation

### ISSUE THREAD

**Issue by cwickham** [merely-useful/merely-useful.github.io#96]
This issue tracks the [Data Manipulation](https://github.com/merely-useful/merely-useful.github.io/blob/925ff17ea8b0b5aa5fa15d219a8b9012e533397c/novice-goals.Rmd#L22-L49) section for the novice R material.

This issue can be closed when:

* [ ] There are an initial set of R exercises corresponding to the outline
* [ ] There is a first draft of the text of the section

**Comment by lwjohnst86** [comment]
Since the branch was merged, closing this.
